/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Array100.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/Array100.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_ARRAY100_H_1E5A4D25C3F5427D4079424172115916
#define DDSC_ARRAY100_H_1E5A4D25C3F5427D4079424172115916

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Array100
{
  uint8_t data[100];
} Array100;

extern const dds_topic_descriptor_t Array100_desc;

#define Array100__alloc() \
((Array100*) dds_alloc (sizeof (Array100)));

#define Array100_free(d,o) \
dds_sample_free ((d), &Array100_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ARRAY100_H_1E5A4D25C3F5427D4079424172115916 */
