/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CdrStreamKeySize.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/CdrStreamKeySize.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_CDRSTREAMKEYSIZE_H_1DF789794B44B19A6C720D4BB6471B5F
#define DDSC_CDRSTREAMKEYSIZE_H_1DF789794B44B19A6C720D4BB6471B5F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CdrStreamKeySize_t1
{
  int32_t a;
  int16_t b;
} CdrStreamKeySize_t1;

extern const dds_topic_descriptor_t CdrStreamKeySize_t1_desc;

#define CdrStreamKeySize_t1__alloc() \
((CdrStreamKeySize_t1*) dds_alloc (sizeof (CdrStreamKeySize_t1)));

#define CdrStreamKeySize_t1_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t1_desc, (o))

typedef struct CdrStreamKeySize_t2
{
  char a;
  int64_t b;
  int16_t c;
} CdrStreamKeySize_t2;

extern const dds_topic_descriptor_t CdrStreamKeySize_t2_desc;

#define CdrStreamKeySize_t2__alloc() \
((CdrStreamKeySize_t2*) dds_alloc (sizeof (CdrStreamKeySize_t2)));

#define CdrStreamKeySize_t2_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t2_desc, (o))

typedef struct CdrStreamKeySize_nested3
{
  char a;
  int64_t b;
  int16_t c;
} CdrStreamKeySize_nested3;

typedef struct CdrStreamKeySize_t3
{
  struct CdrStreamKeySize_nested3 a;
} CdrStreamKeySize_t3;

extern const dds_topic_descriptor_t CdrStreamKeySize_t3_desc;

#define CdrStreamKeySize_t3__alloc() \
((CdrStreamKeySize_t3*) dds_alloc (sizeof (CdrStreamKeySize_t3)));

#define CdrStreamKeySize_t3_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t3_desc, (o))

typedef struct CdrStreamKeySize_nested4
{
  char a;
  int16_t b;
} CdrStreamKeySize_nested4;

typedef struct CdrStreamKeySize_t4
{
  struct CdrStreamKeySize_nested4 a;
  int64_t b;
  char c;
} CdrStreamKeySize_t4;

extern const dds_topic_descriptor_t CdrStreamKeySize_t4_desc;

#define CdrStreamKeySize_t4__alloc() \
((CdrStreamKeySize_t4*) dds_alloc (sizeof (CdrStreamKeySize_t4)));

#define CdrStreamKeySize_t4_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t4_desc, (o))

typedef struct CdrStreamKeySize_t5
{
  int32_t a[5];
} CdrStreamKeySize_t5;

extern const dds_topic_descriptor_t CdrStreamKeySize_t5_desc;

#define CdrStreamKeySize_t5__alloc() \
((CdrStreamKeySize_t5*) dds_alloc (sizeof (CdrStreamKeySize_t5)));

#define CdrStreamKeySize_t5_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t5_desc, (o))

typedef struct CdrStreamKeySize_nested6
{
  int64_t a;
} CdrStreamKeySize_nested6;

typedef struct CdrStreamKeySize_t6
{
  struct CdrStreamKeySize_nested6 a;
  int32_t b[5];
  char c;
  float d;
} CdrStreamKeySize_t6;

extern const dds_topic_descriptor_t CdrStreamKeySize_t6_desc;

#define CdrStreamKeySize_t6__alloc() \
((CdrStreamKeySize_t6*) dds_alloc (sizeof (CdrStreamKeySize_t6)));

#define CdrStreamKeySize_t6_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t6_desc, (o))

typedef struct CdrStreamKeySize_nested7_1
{
  int16_t a;
} CdrStreamKeySize_nested7_1;

typedef struct CdrStreamKeySize_nested7_2
{
  int64_t a;
} CdrStreamKeySize_nested7_2;

typedef struct CdrStreamKeySize_t7
{
  struct CdrStreamKeySize_nested7_1 a;
  struct CdrStreamKeySize_nested7_2 b;
  char c;
  struct CdrStreamKeySize_nested7_1 d;
} CdrStreamKeySize_t7;

extern const dds_topic_descriptor_t CdrStreamKeySize_t7_desc;

#define CdrStreamKeySize_t7__alloc() \
((CdrStreamKeySize_t7*) dds_alloc (sizeof (CdrStreamKeySize_t7)));

#define CdrStreamKeySize_t7_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t7_desc, (o))

typedef struct CdrStreamKeySize_t8
{
  char a[15];
} CdrStreamKeySize_t8;

extern const dds_topic_descriptor_t CdrStreamKeySize_t8_desc;

#define CdrStreamKeySize_t8__alloc() \
((CdrStreamKeySize_t8*) dds_alloc (sizeof (CdrStreamKeySize_t8)));

#define CdrStreamKeySize_t8_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t8_desc, (o))

typedef struct CdrStreamKeySize_t9
{
  int16_t a[6];
} CdrStreamKeySize_t9;

extern const dds_topic_descriptor_t CdrStreamKeySize_t9_desc;

#define CdrStreamKeySize_t9__alloc() \
((CdrStreamKeySize_t9*) dds_alloc (sizeof (CdrStreamKeySize_t9)));

#define CdrStreamKeySize_t9_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t9_desc, (o))

typedef struct CdrStreamKeySize_nested10
{
  int64_t a;
  int32_t b;
} CdrStreamKeySize_nested10;

typedef struct CdrStreamKeySize_t10
{
  struct CdrStreamKeySize_nested10 a;
  struct CdrStreamKeySize_nested10 b;
} CdrStreamKeySize_t10;

extern const dds_topic_descriptor_t CdrStreamKeySize_t10_desc;

#define CdrStreamKeySize_t10__alloc() \
((CdrStreamKeySize_t10*) dds_alloc (sizeof (CdrStreamKeySize_t10)));

#define CdrStreamKeySize_t10_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t10_desc, (o))

typedef struct CdrStreamKeySize_t11
{
  char a[4];
  int64_t b;
} CdrStreamKeySize_t11;

extern const dds_topic_descriptor_t CdrStreamKeySize_t11_desc;

#define CdrStreamKeySize_t11__alloc() \
((CdrStreamKeySize_t11*) dds_alloc (sizeof (CdrStreamKeySize_t11)));

#define CdrStreamKeySize_t11_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t11_desc, (o))

typedef struct CdrStreamKeySize_t12
{
  char a;
  char b[4];
  int32_t c;
} CdrStreamKeySize_t12;

extern const dds_topic_descriptor_t CdrStreamKeySize_t12_desc;

#define CdrStreamKeySize_t12__alloc() \
((CdrStreamKeySize_t12*) dds_alloc (sizeof (CdrStreamKeySize_t12)));

#define CdrStreamKeySize_t12_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t12_desc, (o))

typedef struct CdrStreamKeySize_t13
{
  float a;
  char b;
  double c;
} CdrStreamKeySize_t13;

extern const dds_topic_descriptor_t CdrStreamKeySize_t13_desc;

#define CdrStreamKeySize_t13__alloc() \
((CdrStreamKeySize_t13*) dds_alloc (sizeof (CdrStreamKeySize_t13)));

#define CdrStreamKeySize_t13_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t13_desc, (o))

typedef struct CdrStreamKeySize_t14
{
  char b;
  double a;
  float c;
} CdrStreamKeySize_t14;

extern const dds_topic_descriptor_t CdrStreamKeySize_t14_desc;

#define CdrStreamKeySize_t14__alloc() \
((CdrStreamKeySize_t14*) dds_alloc (sizeof (CdrStreamKeySize_t14)));

#define CdrStreamKeySize_t14_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t14_desc, (o))

typedef struct CdrStreamKeySize_t15
{
  char c1;
  char c2;
  char c3;
  int32_t l1;
  int32_t l2;
} CdrStreamKeySize_t15;

extern const dds_topic_descriptor_t CdrStreamKeySize_t15_desc;

#define CdrStreamKeySize_t15__alloc() \
((CdrStreamKeySize_t15*) dds_alloc (sizeof (CdrStreamKeySize_t15)));

#define CdrStreamKeySize_t15_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t15_desc, (o))

typedef enum CdrStreamKeySize_e16
{
  CdrStreamKeySize_E16_0,
  CdrStreamKeySize_E16_1
} CdrStreamKeySize_e16;

#define CdrStreamKeySize_e16__alloc() \
((CdrStreamKeySize_e16*) dds_alloc (sizeof (CdrStreamKeySize_e16)));

typedef struct CdrStreamKeySize_t16
{
  CdrStreamKeySize_e16 a;
} CdrStreamKeySize_t16;

extern const dds_topic_descriptor_t CdrStreamKeySize_t16_desc;

#define CdrStreamKeySize_t16__alloc() \
((CdrStreamKeySize_t16*) dds_alloc (sizeof (CdrStreamKeySize_t16)));

#define CdrStreamKeySize_t16_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t16_desc, (o))

typedef enum CdrStreamKeySize_e17
{
  CdrStreamKeySize_E17_0,
  CdrStreamKeySize_E17_1
} CdrStreamKeySize_e17;

#define CdrStreamKeySize_e17__alloc() \
((CdrStreamKeySize_e17*) dds_alloc (sizeof (CdrStreamKeySize_e17)));

typedef struct CdrStreamKeySize_t17
{
  CdrStreamKeySize_e17 a;
} CdrStreamKeySize_t17;

extern const dds_topic_descriptor_t CdrStreamKeySize_t17_desc;

#define CdrStreamKeySize_t17__alloc() \
((CdrStreamKeySize_t17*) dds_alloc (sizeof (CdrStreamKeySize_t17)));

#define CdrStreamKeySize_t17_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t17_desc, (o))

typedef enum CdrStreamKeySize_e18
{
  CdrStreamKeySize_E18_0,
  CdrStreamKeySize_E18_1
} CdrStreamKeySize_e18;

#define CdrStreamKeySize_e18__alloc() \
((CdrStreamKeySize_e18*) dds_alloc (sizeof (CdrStreamKeySize_e18)));

typedef struct CdrStreamKeySize_t18
{
  char a;
  CdrStreamKeySize_e18 b[4];
} CdrStreamKeySize_t18;

extern const dds_topic_descriptor_t CdrStreamKeySize_t18_desc;

#define CdrStreamKeySize_t18__alloc() \
((CdrStreamKeySize_t18*) dds_alloc (sizeof (CdrStreamKeySize_t18)));

#define CdrStreamKeySize_t18_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t18_desc, (o))

typedef uint32_t CdrStreamKeySize_bm19;
#define CdrStreamKeySize_BM19_0 (1lu << 0)
#define CdrStreamKeySize_BM19_1 (1lu << 1)
typedef struct CdrStreamKeySize_t19
{
  CdrStreamKeySize_bm19 a;
} CdrStreamKeySize_t19;

extern const dds_topic_descriptor_t CdrStreamKeySize_t19_desc;

#define CdrStreamKeySize_t19__alloc() \
((CdrStreamKeySize_t19*) dds_alloc (sizeof (CdrStreamKeySize_t19)));

#define CdrStreamKeySize_t19_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t19_desc, (o))

typedef uint8_t CdrStreamKeySize_bm20;
#define CdrStreamKeySize_BM20_0 (1 << 0)
#define CdrStreamKeySize_BM20_1 (1 << 1)
typedef struct CdrStreamKeySize_t20
{
  CdrStreamKeySize_bm20 a;
} CdrStreamKeySize_t20;

extern const dds_topic_descriptor_t CdrStreamKeySize_t20_desc;

#define CdrStreamKeySize_t20__alloc() \
((CdrStreamKeySize_t20*) dds_alloc (sizeof (CdrStreamKeySize_t20)));

#define CdrStreamKeySize_t20_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t20_desc, (o))

typedef uint64_t CdrStreamKeySize_bm21;
#define CdrStreamKeySize_BM21_0 (1llu << 0)
#define CdrStreamKeySize_BM21_1 (1llu << 1)
typedef struct CdrStreamKeySize_t21
{
  char a;
  CdrStreamKeySize_bm21 b[1];
} CdrStreamKeySize_t21;

extern const dds_topic_descriptor_t CdrStreamKeySize_t21_desc;

#define CdrStreamKeySize_t21__alloc() \
((CdrStreamKeySize_t21*) dds_alloc (sizeof (CdrStreamKeySize_t21)));

#define CdrStreamKeySize_t21_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t21_desc, (o))

typedef struct CdrStreamKeySize_t22
{
  int32_t a;
} CdrStreamKeySize_t22;

extern const dds_topic_descriptor_t CdrStreamKeySize_t22_desc;

#define CdrStreamKeySize_t22__alloc() \
((CdrStreamKeySize_t22*) dds_alloc (sizeof (CdrStreamKeySize_t22)));

#define CdrStreamKeySize_t22_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t22_desc, (o))

typedef struct CdrStreamKeySize_t23
{
  int32_t a;
} CdrStreamKeySize_t23;

extern const dds_topic_descriptor_t CdrStreamKeySize_t23_desc;

#define CdrStreamKeySize_t23__alloc() \
((CdrStreamKeySize_t23*) dds_alloc (sizeof (CdrStreamKeySize_t23)));

#define CdrStreamKeySize_t23_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t23_desc, (o))

typedef struct CdrStreamKeySize_nested24
{
  int32_t a;
} CdrStreamKeySize_nested24;

typedef struct CdrStreamKeySize_t24
{
  struct CdrStreamKeySize_nested24 a;
} CdrStreamKeySize_t24;

extern const dds_topic_descriptor_t CdrStreamKeySize_t24_desc;

#define CdrStreamKeySize_t24__alloc() \
((CdrStreamKeySize_t24*) dds_alloc (sizeof (CdrStreamKeySize_t24)));

#define CdrStreamKeySize_t24_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t24_desc, (o))

typedef struct CdrStreamKeySize_nested25
{
  int32_t a;
} CdrStreamKeySize_nested25;

typedef struct CdrStreamKeySize_t25
{
  struct CdrStreamKeySize_nested25 a;
} CdrStreamKeySize_t25;

extern const dds_topic_descriptor_t CdrStreamKeySize_t25_desc;

#define CdrStreamKeySize_t25__alloc() \
((CdrStreamKeySize_t25*) dds_alloc (sizeof (CdrStreamKeySize_t25)));

#define CdrStreamKeySize_t25_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t25_desc, (o))

typedef struct CdrStreamKeySize_nested26
{
  int8_t a;
} CdrStreamKeySize_nested26;

typedef struct CdrStreamKeySize_t26
{
  struct CdrStreamKeySize_nested26 a;
} CdrStreamKeySize_t26;

extern const dds_topic_descriptor_t CdrStreamKeySize_t26_desc;

#define CdrStreamKeySize_t26__alloc() \
((CdrStreamKeySize_t26*) dds_alloc (sizeof (CdrStreamKeySize_t26)));

#define CdrStreamKeySize_t26_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t26_desc, (o))

typedef struct CdrStreamKeySize_nested27
{
  int32_t a;
  uint8_t b;
} CdrStreamKeySize_nested27;

typedef struct CdrStreamKeySize_t27
{
  struct CdrStreamKeySize_nested27 a;
} CdrStreamKeySize_t27;

extern const dds_topic_descriptor_t CdrStreamKeySize_t27_desc;

#define CdrStreamKeySize_t27__alloc() \
((CdrStreamKeySize_t27*) dds_alloc (sizeof (CdrStreamKeySize_t27)));

#define CdrStreamKeySize_t27_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t27_desc, (o))

typedef enum CdrStreamKeySize_e28
{
  CdrStreamKeySize_E28_0,
  CdrStreamKeySize_E28_1
} CdrStreamKeySize_e28;

#define CdrStreamKeySize_e28__alloc() \
((CdrStreamKeySize_e28*) dds_alloc (sizeof (CdrStreamKeySize_e28)));

typedef struct CdrStreamKeySize_t28
{
  CdrStreamKeySize_e28 a[2];
} CdrStreamKeySize_t28;

extern const dds_topic_descriptor_t CdrStreamKeySize_t28_desc;

#define CdrStreamKeySize_t28__alloc() \
((CdrStreamKeySize_t28*) dds_alloc (sizeof (CdrStreamKeySize_t28)));

#define CdrStreamKeySize_t28_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t28_desc, (o))

typedef struct CdrStreamKeySize_base29
{
  int32_t k;
} CdrStreamKeySize_base29;

typedef struct CdrStreamKeySize_t29
{
  struct CdrStreamKeySize_base29 parent;
  int32_t a;
} CdrStreamKeySize_t29;

extern const dds_topic_descriptor_t CdrStreamKeySize_t29_desc;

#define CdrStreamKeySize_t29__alloc() \
((CdrStreamKeySize_t29*) dds_alloc (sizeof (CdrStreamKeySize_t29)));

#define CdrStreamKeySize_t29_free(d,o) \
dds_sample_free ((d), &CdrStreamKeySize_t29_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CDRSTREAMKEYSIZE_H_1DF789794B44B19A6C720D4BB6471B5F */
