/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CdrStreamOptimize.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/CdrStreamOptimize.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_CDRSTREAMOPTIMIZE_H_55D4681E72962337EEAE0FA506039DBE
#define DDSC_CDRSTREAMOPTIMIZE_H_55D4681E72962337EEAE0FA506039DBE

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CdrStreamOptimize_t1
{
  int32_t f1;
} CdrStreamOptimize_t1;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_desc;

#define CdrStreamOptimize_t1__alloc() \
((CdrStreamOptimize_t1*) dds_alloc (sizeof (CdrStreamOptimize_t1)));

#define CdrStreamOptimize_t1_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_desc, (o))

typedef struct CdrStreamOptimize_t1_a
{
  int32_t f1;
} CdrStreamOptimize_t1_a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_a_desc;

#define CdrStreamOptimize_t1_a__alloc() \
((CdrStreamOptimize_t1_a*) dds_alloc (sizeof (CdrStreamOptimize_t1_a)));

#define CdrStreamOptimize_t1_a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_a_desc, (o))

typedef struct CdrStreamOptimize_t1_m
{
  int32_t f1;
} CdrStreamOptimize_t1_m;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_m_desc;

#define CdrStreamOptimize_t1_m__alloc() \
((CdrStreamOptimize_t1_m*) dds_alloc (sizeof (CdrStreamOptimize_t1_m)));

#define CdrStreamOptimize_t1_m_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_m_desc, (o))

typedef struct CdrStreamOptimize_t2
{
  uint8_t f1;
  int64_t f2;
} CdrStreamOptimize_t2;

extern const dds_topic_descriptor_t CdrStreamOptimize_t2_desc;

#define CdrStreamOptimize_t2__alloc() \
((CdrStreamOptimize_t2*) dds_alloc (sizeof (CdrStreamOptimize_t2)));

#define CdrStreamOptimize_t2_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t2_desc, (o))

typedef struct CdrStreamOptimize_t3
{
  uint8_t * f1;
} CdrStreamOptimize_t3;

extern const dds_topic_descriptor_t CdrStreamOptimize_t3_desc;

#define CdrStreamOptimize_t3__alloc() \
((CdrStreamOptimize_t3*) dds_alloc (sizeof (CdrStreamOptimize_t3)));

#define CdrStreamOptimize_t3_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t3_desc, (o))

typedef struct CdrStreamOptimize_n4
{
  int32_t f1;
  uint8_t f2;
} CdrStreamOptimize_n4;

typedef struct CdrStreamOptimize_t4
{
  struct CdrStreamOptimize_n4 f1;
} CdrStreamOptimize_t4;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4_desc;

#define CdrStreamOptimize_t4__alloc() \
((CdrStreamOptimize_t4*) dds_alloc (sizeof (CdrStreamOptimize_t4)));

#define CdrStreamOptimize_t4_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4_desc, (o))

typedef struct CdrStreamOptimize_t4a
{
  struct CdrStreamOptimize_n4 f1;
  struct CdrStreamOptimize_n4 f2;
} CdrStreamOptimize_t4a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4a_desc;

#define CdrStreamOptimize_t4a__alloc() \
((CdrStreamOptimize_t4a*) dds_alloc (sizeof (CdrStreamOptimize_t4a)));

#define CdrStreamOptimize_t4a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4a_desc, (o))

typedef struct CdrStreamOptimize_t4b
{
  struct CdrStreamOptimize_t4a f1;
  struct CdrStreamOptimize_t4a f2;
} CdrStreamOptimize_t4b;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4b_desc;

#define CdrStreamOptimize_t4b__alloc() \
((CdrStreamOptimize_t4b*) dds_alloc (sizeof (CdrStreamOptimize_t4b)));

#define CdrStreamOptimize_t4b_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4b_desc, (o))

typedef struct CdrStreamOptimize_n5
{
  uint8_t f1;
  int64_t f2;
} CdrStreamOptimize_n5;

typedef struct CdrStreamOptimize_t5
{
  struct CdrStreamOptimize_n5 f1;
} CdrStreamOptimize_t5;

extern const dds_topic_descriptor_t CdrStreamOptimize_t5_desc;

#define CdrStreamOptimize_t5__alloc() \
((CdrStreamOptimize_t5*) dds_alloc (sizeof (CdrStreamOptimize_t5)));

#define CdrStreamOptimize_t5_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t5_desc, (o))

typedef struct CdrStreamOptimize_t5a
{
  struct CdrStreamOptimize_n5 f1[3];
} CdrStreamOptimize_t5a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t5a_desc;

#define CdrStreamOptimize_t5a__alloc() \
((CdrStreamOptimize_t5a*) dds_alloc (sizeof (CdrStreamOptimize_t5a)));

#define CdrStreamOptimize_t5a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t5a_desc, (o))

typedef enum CdrStreamOptimize_en6
{
  CdrStreamOptimize_E6_1,
  CdrStreamOptimize_E6_2
} CdrStreamOptimize_en6;

#define CdrStreamOptimize_en6__alloc() \
((CdrStreamOptimize_en6*) dds_alloc (sizeof (CdrStreamOptimize_en6)));

typedef struct CdrStreamOptimize_t6
{
  uint8_t f1;
  CdrStreamOptimize_en6 f2;
  uint8_t f3;
  int16_t f5;
  int32_t f6;
} CdrStreamOptimize_t6;

extern const dds_topic_descriptor_t CdrStreamOptimize_t6_desc;

#define CdrStreamOptimize_t6__alloc() \
((CdrStreamOptimize_t6*) dds_alloc (sizeof (CdrStreamOptimize_t6)));

#define CdrStreamOptimize_t6_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t6_desc, (o))

typedef struct CdrStreamOptimize_t6a
{
  bool f1;
  CdrStreamOptimize_en6 f2;
  uint8_t f3;
  int16_t f5;
  int32_t f6;
} CdrStreamOptimize_t6a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t6a_desc;

#define CdrStreamOptimize_t6a__alloc() \
((CdrStreamOptimize_t6a*) dds_alloc (sizeof (CdrStreamOptimize_t6a)));

#define CdrStreamOptimize_t6a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t6a_desc, (o))

typedef struct CdrStreamOptimize_n7
{
  uint8_t f1;
  int16_t f2;
} CdrStreamOptimize_n7;

typedef struct CdrStreamOptimize_t7
{
  uint8_t f1;
  struct CdrStreamOptimize_n7 f2;
  int16_t f3;
} CdrStreamOptimize_t7;

extern const dds_topic_descriptor_t CdrStreamOptimize_t7_desc;

#define CdrStreamOptimize_t7__alloc() \
((CdrStreamOptimize_t7*) dds_alloc (sizeof (CdrStreamOptimize_t7)));

#define CdrStreamOptimize_t7_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t7_desc, (o))

typedef struct CdrStreamOptimize_n8
{
  int32_t f1;
} CdrStreamOptimize_n8;

typedef struct CdrStreamOptimize_t8
{
  int32_t f1;
  struct CdrStreamOptimize_n8 f2;
} CdrStreamOptimize_t8;

extern const dds_topic_descriptor_t CdrStreamOptimize_t8_desc;

#define CdrStreamOptimize_t8__alloc() \
((CdrStreamOptimize_t8*) dds_alloc (sizeof (CdrStreamOptimize_t8)));

#define CdrStreamOptimize_t8_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t8_desc, (o))

typedef uint8_t CdrStreamOptimize_bm9;
#define CdrStreamOptimize_B9_1 (1 << 0)
#define CdrStreamOptimize_B9_2 (1 << 1)
#define CdrStreamOptimize_B9_3 (1 << 2)
typedef struct CdrStreamOptimize_t9
{
  CdrStreamOptimize_bm9 f1[3];
} CdrStreamOptimize_t9;

extern const dds_topic_descriptor_t CdrStreamOptimize_t9_desc;

#define CdrStreamOptimize_t9__alloc() \
((CdrStreamOptimize_t9*) dds_alloc (sizeof (CdrStreamOptimize_t9)));

#define CdrStreamOptimize_t9_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t9_desc, (o))

typedef enum CdrStreamOptimize_en10
{
  CdrStreamOptimize_E10_1,
  CdrStreamOptimize_E10_2
} CdrStreamOptimize_en10;

#define CdrStreamOptimize_en10__alloc() \
((CdrStreamOptimize_en10*) dds_alloc (sizeof (CdrStreamOptimize_en10)));

typedef struct CdrStreamOptimize_t10
{
  CdrStreamOptimize_en10 f1[3];
} CdrStreamOptimize_t10;

extern const dds_topic_descriptor_t CdrStreamOptimize_t10_desc;

#define CdrStreamOptimize_t10__alloc() \
((CdrStreamOptimize_t10*) dds_alloc (sizeof (CdrStreamOptimize_t10)));

#define CdrStreamOptimize_t10_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t10_desc, (o))

typedef struct CdrStreamOptimize_t11
{
  int32_t f1[100];
  int32_t f2;
  float f3;
  char f4;
  uint8_t f5;
} CdrStreamOptimize_t11;

extern const dds_topic_descriptor_t CdrStreamOptimize_t11_desc;

#define CdrStreamOptimize_t11__alloc() \
((CdrStreamOptimize_t11*) dds_alloc (sizeof (CdrStreamOptimize_t11)));

#define CdrStreamOptimize_t11_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t11_desc, (o))

typedef struct CdrStreamOptimize_t11a
{
  int32_t f1[100];
  int32_t f2;
  float f3;
  char f4;
  bool f5;
} CdrStreamOptimize_t11a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t11a_desc;

#define CdrStreamOptimize_t11a__alloc() \
((CdrStreamOptimize_t11a*) dds_alloc (sizeof (CdrStreamOptimize_t11a)));

#define CdrStreamOptimize_t11a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t11a_desc, (o))

typedef uint32_t CdrStreamOptimize_bm12;
#define CdrStreamOptimize_BM12_0 (1lu << 0)
#define CdrStreamOptimize_BM12_1 (1lu << 1)
typedef struct CdrStreamOptimize_t12
{
  CdrStreamOptimize_bm12 f1;
} CdrStreamOptimize_t12;

extern const dds_topic_descriptor_t CdrStreamOptimize_t12_desc;

#define CdrStreamOptimize_t12__alloc() \
((CdrStreamOptimize_t12*) dds_alloc (sizeof (CdrStreamOptimize_t12)));

#define CdrStreamOptimize_t12_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t12_desc, (o))

typedef uint8_t CdrStreamOptimize_bm13;
#define CdrStreamOptimize_BM13_0 (1 << 0)
#define CdrStreamOptimize_BM13_1 (1 << 1)
typedef struct CdrStreamOptimize_t13
{
  CdrStreamOptimize_bm13 f1;
} CdrStreamOptimize_t13;

extern const dds_topic_descriptor_t CdrStreamOptimize_t13_desc;

#define CdrStreamOptimize_t13__alloc() \
((CdrStreamOptimize_t13*) dds_alloc (sizeof (CdrStreamOptimize_t13)));

#define CdrStreamOptimize_t13_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t13_desc, (o))

typedef uint64_t CdrStreamOptimize_bm14;
#define CdrStreamOptimize_BM14_0 (1llu << 0)
#define CdrStreamOptimize_BM14_1 (1llu << 1)
typedef struct CdrStreamOptimize_t14
{
  CdrStreamOptimize_bm14 f1;
} CdrStreamOptimize_t14;

extern const dds_topic_descriptor_t CdrStreamOptimize_t14_desc;

#define CdrStreamOptimize_t14__alloc() \
((CdrStreamOptimize_t14*) dds_alloc (sizeof (CdrStreamOptimize_t14)));

#define CdrStreamOptimize_t14_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t14_desc, (o))

typedef struct CdrStreamOptimize_n15_1
{
  char f3[100];
} CdrStreamOptimize_n15_1;

typedef struct CdrStreamOptimize_n15_2
{
  struct CdrStreamOptimize_n15_1 f2;
} CdrStreamOptimize_n15_2;

typedef struct CdrStreamOptimize_t15
{
  struct CdrStreamOptimize_n15_2 f1;
} CdrStreamOptimize_t15;

extern const dds_topic_descriptor_t CdrStreamOptimize_t15_desc;

#define CdrStreamOptimize_t15__alloc() \
((CdrStreamOptimize_t15*) dds_alloc (sizeof (CdrStreamOptimize_t15)));

#define CdrStreamOptimize_t15_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t15_desc, (o))

typedef struct CdrStreamOptimize_t16
{
  char * f1;
} CdrStreamOptimize_t16;

extern const dds_topic_descriptor_t CdrStreamOptimize_t16_desc;

#define CdrStreamOptimize_t16__alloc() \
((CdrStreamOptimize_t16*) dds_alloc (sizeof (CdrStreamOptimize_t16)));

#define CdrStreamOptimize_t16_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t16_desc, (o))

typedef struct CdrStreamOptimize_t17
{
  char f1[101];
} CdrStreamOptimize_t17;

extern const dds_topic_descriptor_t CdrStreamOptimize_t17_desc;

#define CdrStreamOptimize_t17__alloc() \
((CdrStreamOptimize_t17*) dds_alloc (sizeof (CdrStreamOptimize_t17)));

#define CdrStreamOptimize_t17_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t17_desc, (o))

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

typedef struct CdrStreamOptimize_t18
{
  dds_sequence_long f1;
} CdrStreamOptimize_t18;

extern const dds_topic_descriptor_t CdrStreamOptimize_t18_desc;

#define CdrStreamOptimize_t18__alloc() \
((CdrStreamOptimize_t18*) dds_alloc (sizeof (CdrStreamOptimize_t18)));

#define CdrStreamOptimize_t18_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t18_desc, (o))

typedef struct CdrStreamOptimize_t19
{
  int32_t * f1;
} CdrStreamOptimize_t19;

extern const dds_topic_descriptor_t CdrStreamOptimize_t19_desc;

#define CdrStreamOptimize_t19__alloc() \
((CdrStreamOptimize_t19*) dds_alloc (sizeof (CdrStreamOptimize_t19)));

#define CdrStreamOptimize_t19_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t19_desc, (o))

typedef struct CdrStreamOptimize_t20
{
  int32_t (* f1)[100];
} CdrStreamOptimize_t20;

extern const dds_topic_descriptor_t CdrStreamOptimize_t20_desc;

#define CdrStreamOptimize_t20__alloc() \
((CdrStreamOptimize_t20*) dds_alloc (sizeof (CdrStreamOptimize_t20)));

#define CdrStreamOptimize_t20_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t20_desc, (o))

typedef enum CdrStreamOptimize_en21
{
  CdrStreamOptimize_E21_0,
  CdrStreamOptimize_E21_1
} CdrStreamOptimize_en21;

#define CdrStreamOptimize_en21__alloc() \
((CdrStreamOptimize_en21*) dds_alloc (sizeof (CdrStreamOptimize_en21)));

typedef struct CdrStreamOptimize_t21
{
  CdrStreamOptimize_en21 f1;
} CdrStreamOptimize_t21;

extern const dds_topic_descriptor_t CdrStreamOptimize_t21_desc;

#define CdrStreamOptimize_t21__alloc() \
((CdrStreamOptimize_t21*) dds_alloc (sizeof (CdrStreamOptimize_t21)));

#define CdrStreamOptimize_t21_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t21_desc, (o))

typedef enum CdrStreamOptimize_en22
{
  CdrStreamOptimize_E22_0,
  CdrStreamOptimize_E22_1
} CdrStreamOptimize_en22;

#define CdrStreamOptimize_en22__alloc() \
((CdrStreamOptimize_en22*) dds_alloc (sizeof (CdrStreamOptimize_en22)));

typedef struct CdrStreamOptimize_t22
{
  CdrStreamOptimize_en22 f1;
} CdrStreamOptimize_t22;

extern const dds_topic_descriptor_t CdrStreamOptimize_t22_desc;

#define CdrStreamOptimize_t22__alloc() \
((CdrStreamOptimize_t22*) dds_alloc (sizeof (CdrStreamOptimize_t22)));

#define CdrStreamOptimize_t22_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t22_desc, (o))

typedef struct CdrStreamOptimize_n23
{
  int32_t s1;
} CdrStreamOptimize_n23;

typedef struct CdrStreamOptimize_t23
{
  struct CdrStreamOptimize_n23 * f1;
} CdrStreamOptimize_t23;

extern const dds_topic_descriptor_t CdrStreamOptimize_t23_desc;

#define CdrStreamOptimize_t23__alloc() \
((CdrStreamOptimize_t23*) dds_alloc (sizeof (CdrStreamOptimize_t23)));

#define CdrStreamOptimize_t23_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t23_desc, (o))

typedef struct CdrStreamOptimize_n24
{
  int32_t * s1;
} CdrStreamOptimize_n24;

typedef struct CdrStreamOptimize_t24
{
  struct CdrStreamOptimize_n24 f1;
} CdrStreamOptimize_t24;

extern const dds_topic_descriptor_t CdrStreamOptimize_t24_desc;

#define CdrStreamOptimize_t24__alloc() \
((CdrStreamOptimize_t24*) dds_alloc (sizeof (CdrStreamOptimize_t24)));

#define CdrStreamOptimize_t24_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t24_desc, (o))

typedef struct CdrStreamOptimize_t25
{
  int16_t _d;
  union
  {
    int32_t f1;
  } _u;
} CdrStreamOptimize_t25;

extern const dds_topic_descriptor_t CdrStreamOptimize_t25_desc;

#define CdrStreamOptimize_t25__alloc() \
((CdrStreamOptimize_t25*) dds_alloc (sizeof (CdrStreamOptimize_t25)));

#define CdrStreamOptimize_t25_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t25_desc, (o))

typedef struct CdrStreamOptimize_u26
{
  int16_t _d;
  union
  {
    int32_t u1;
  } _u;
} CdrStreamOptimize_u26;

typedef struct CdrStreamOptimize_t26
{
  struct CdrStreamOptimize_u26 f1;
} CdrStreamOptimize_t26;

extern const dds_topic_descriptor_t CdrStreamOptimize_t26_desc;

#define CdrStreamOptimize_t26__alloc() \
((CdrStreamOptimize_t26*) dds_alloc (sizeof (CdrStreamOptimize_t26)));

#define CdrStreamOptimize_t26_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t26_desc, (o))

typedef struct CdrStreamOptimize_b27
{
  int32_t b1;
} CdrStreamOptimize_b27;

typedef struct CdrStreamOptimize_t27
{
  struct CdrStreamOptimize_b27 parent;
  int64_t f1;
} CdrStreamOptimize_t27;

extern const dds_topic_descriptor_t CdrStreamOptimize_t27_desc;

#define CdrStreamOptimize_t27__alloc() \
((CdrStreamOptimize_t27*) dds_alloc (sizeof (CdrStreamOptimize_t27)));

#define CdrStreamOptimize_t27_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t27_desc, (o))

typedef struct CdrStreamOptimize_t28
{
  bool f1[2];
} CdrStreamOptimize_t28;

extern const dds_topic_descriptor_t CdrStreamOptimize_t28_desc;

#define CdrStreamOptimize_t28__alloc() \
((CdrStreamOptimize_t28*) dds_alloc (sizeof (CdrStreamOptimize_t28)));

#define CdrStreamOptimize_t28_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t28_desc, (o))

typedef struct CdrStreamOptimize_b29
{
  int32_t b1;
} CdrStreamOptimize_b29;

typedef struct CdrStreamOptimize_t29
{
  struct CdrStreamOptimize_b29 parent;
  bool f1;
} CdrStreamOptimize_t29;

extern const dds_topic_descriptor_t CdrStreamOptimize_t29_desc;

#define CdrStreamOptimize_t29__alloc() \
((CdrStreamOptimize_t29*) dds_alloc (sizeof (CdrStreamOptimize_t29)));

#define CdrStreamOptimize_t29_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t29_desc, (o))

typedef struct CdrStreamOptimize_b30
{
  bool b1;
} CdrStreamOptimize_b30;

typedef struct CdrStreamOptimize_t30
{
  struct CdrStreamOptimize_b30 parent;
  int32_t f1;
} CdrStreamOptimize_t30;

extern const dds_topic_descriptor_t CdrStreamOptimize_t30_desc;

#define CdrStreamOptimize_t30__alloc() \
((CdrStreamOptimize_t30*) dds_alloc (sizeof (CdrStreamOptimize_t30)));

#define CdrStreamOptimize_t30_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t30_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CDRSTREAMOPTIMIZE_H_55D4681E72962337EEAE0FA506039DBE */
