/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CdrStreamKeyExt.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/CdrStreamKeyExt.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_CDRSTREAMKEYEXT_H_A8626E385FFB4A98197A9340F3D55976
#define DDSC_CDRSTREAMKEYEXT_H_A8626E385FFB4A98197A9340F3D55976

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CdrStreamKeyExt_t1
{
  int32_t a;
} CdrStreamKeyExt_t1;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t1_desc;

#define CdrStreamKeyExt_t1__alloc() \
((CdrStreamKeyExt_t1*) dds_alloc (sizeof (CdrStreamKeyExt_t1)));

#define CdrStreamKeyExt_t1_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t1_desc, (o))

typedef struct CdrStreamKeyExt_t1a
{
  int32_t * a;
} CdrStreamKeyExt_t1a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t1a_desc;

#define CdrStreamKeyExt_t1a__alloc() \
((CdrStreamKeyExt_t1a*) dds_alloc (sizeof (CdrStreamKeyExt_t1a)));

#define CdrStreamKeyExt_t1a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t1a_desc, (o))

typedef struct CdrStreamKeyExt_t2
{
  int32_t a;
} CdrStreamKeyExt_t2;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t2_desc;

#define CdrStreamKeyExt_t2__alloc() \
((CdrStreamKeyExt_t2*) dds_alloc (sizeof (CdrStreamKeyExt_t2)));

#define CdrStreamKeyExt_t2_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t2_desc, (o))

typedef struct CdrStreamKeyExt_t3
{
  int32_t a;
} CdrStreamKeyExt_t3;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t3_desc;

#define CdrStreamKeyExt_t3__alloc() \
((CdrStreamKeyExt_t3*) dds_alloc (sizeof (CdrStreamKeyExt_t3)));

#define CdrStreamKeyExt_t3_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t3_desc, (o))

typedef struct CdrStreamKeyExt_nested4
{
  int32_t a;
} CdrStreamKeyExt_nested4;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested4_desc;

#define CdrStreamKeyExt_nested4__alloc() \
((CdrStreamKeyExt_nested4*) dds_alloc (sizeof (CdrStreamKeyExt_nested4)));

#define CdrStreamKeyExt_nested4_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested4_desc, (o))

typedef struct CdrStreamKeyExt_t4
{
  int32_t a;
  struct CdrStreamKeyExt_nested4 b;
} CdrStreamKeyExt_t4;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t4_desc;

#define CdrStreamKeyExt_t4__alloc() \
((CdrStreamKeyExt_t4*) dds_alloc (sizeof (CdrStreamKeyExt_t4)));

#define CdrStreamKeyExt_t4_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t4_desc, (o))

typedef struct CdrStreamKeyExt_nested4a
{
  int32_t a;
} CdrStreamKeyExt_nested4a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested4a_desc;

#define CdrStreamKeyExt_nested4a__alloc() \
((CdrStreamKeyExt_nested4a*) dds_alloc (sizeof (CdrStreamKeyExt_nested4a)));

#define CdrStreamKeyExt_nested4a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested4a_desc, (o))

typedef struct CdrStreamKeyExt_t4a
{
  int32_t a;
  struct CdrStreamKeyExt_nested4a b;
} CdrStreamKeyExt_t4a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t4a_desc;

#define CdrStreamKeyExt_t4a__alloc() \
((CdrStreamKeyExt_t4a*) dds_alloc (sizeof (CdrStreamKeyExt_t4a)));

#define CdrStreamKeyExt_t4a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t4a_desc, (o))

typedef struct CdrStreamKeyExt_nested4b
{
  int32_t a;
} CdrStreamKeyExt_nested4b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested4b_desc;

#define CdrStreamKeyExt_nested4b__alloc() \
((CdrStreamKeyExt_nested4b*) dds_alloc (sizeof (CdrStreamKeyExt_nested4b)));

#define CdrStreamKeyExt_nested4b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested4b_desc, (o))

typedef struct CdrStreamKeyExt_t4b
{
  int32_t a;
  struct CdrStreamKeyExt_nested4b b;
} CdrStreamKeyExt_t4b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t4b_desc;

#define CdrStreamKeyExt_t4b__alloc() \
((CdrStreamKeyExt_t4b*) dds_alloc (sizeof (CdrStreamKeyExt_t4b)));

#define CdrStreamKeyExt_t4b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t4b_desc, (o))

typedef struct CdrStreamKeyExt_nested5
{
  int32_t a;
} CdrStreamKeyExt_nested5;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested5_desc;

#define CdrStreamKeyExt_nested5__alloc() \
((CdrStreamKeyExt_nested5*) dds_alloc (sizeof (CdrStreamKeyExt_nested5)));

#define CdrStreamKeyExt_nested5_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested5_desc, (o))

typedef struct CdrStreamKeyExt_t5
{
  int32_t a;
  struct CdrStreamKeyExt_nested5 b;
} CdrStreamKeyExt_t5;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t5_desc;

#define CdrStreamKeyExt_t5__alloc() \
((CdrStreamKeyExt_t5*) dds_alloc (sizeof (CdrStreamKeyExt_t5)));

#define CdrStreamKeyExt_t5_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t5_desc, (o))

typedef struct CdrStreamKeyExt_nested5a
{
  int32_t a;
} CdrStreamKeyExt_nested5a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested5a_desc;

#define CdrStreamKeyExt_nested5a__alloc() \
((CdrStreamKeyExt_nested5a*) dds_alloc (sizeof (CdrStreamKeyExt_nested5a)));

#define CdrStreamKeyExt_nested5a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested5a_desc, (o))

typedef struct CdrStreamKeyExt_t5a
{
  int32_t a;
  struct CdrStreamKeyExt_nested5a b;
} CdrStreamKeyExt_t5a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t5a_desc;

#define CdrStreamKeyExt_t5a__alloc() \
((CdrStreamKeyExt_t5a*) dds_alloc (sizeof (CdrStreamKeyExt_t5a)));

#define CdrStreamKeyExt_t5a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t5a_desc, (o))

typedef struct CdrStreamKeyExt_nested5b
{
  int32_t a;
} CdrStreamKeyExt_nested5b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested5b_desc;

#define CdrStreamKeyExt_nested5b__alloc() \
((CdrStreamKeyExt_nested5b*) dds_alloc (sizeof (CdrStreamKeyExt_nested5b)));

#define CdrStreamKeyExt_nested5b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested5b_desc, (o))

typedef struct CdrStreamKeyExt_t5b
{
  int32_t a;
  struct CdrStreamKeyExt_nested5b b;
} CdrStreamKeyExt_t5b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t5b_desc;

#define CdrStreamKeyExt_t5b__alloc() \
((CdrStreamKeyExt_t5b*) dds_alloc (sizeof (CdrStreamKeyExt_t5b)));

#define CdrStreamKeyExt_t5b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t5b_desc, (o))

typedef struct CdrStreamKeyExt_nested6
{
  int32_t a;
} CdrStreamKeyExt_nested6;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested6_desc;

#define CdrStreamKeyExt_nested6__alloc() \
((CdrStreamKeyExt_nested6*) dds_alloc (sizeof (CdrStreamKeyExt_nested6)));

#define CdrStreamKeyExt_nested6_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested6_desc, (o))

typedef struct CdrStreamKeyExt_t6
{
  int32_t a;
  struct CdrStreamKeyExt_nested6 b;
} CdrStreamKeyExt_t6;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t6_desc;

#define CdrStreamKeyExt_t6__alloc() \
((CdrStreamKeyExt_t6*) dds_alloc (sizeof (CdrStreamKeyExt_t6)));

#define CdrStreamKeyExt_t6_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t6_desc, (o))

typedef struct CdrStreamKeyExt_nested6a
{
  int32_t a;
} CdrStreamKeyExt_nested6a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested6a_desc;

#define CdrStreamKeyExt_nested6a__alloc() \
((CdrStreamKeyExt_nested6a*) dds_alloc (sizeof (CdrStreamKeyExt_nested6a)));

#define CdrStreamKeyExt_nested6a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested6a_desc, (o))

typedef struct CdrStreamKeyExt_t6a
{
  int32_t a;
  struct CdrStreamKeyExt_nested6a b;
} CdrStreamKeyExt_t6a;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t6a_desc;

#define CdrStreamKeyExt_t6a__alloc() \
((CdrStreamKeyExt_t6a*) dds_alloc (sizeof (CdrStreamKeyExt_t6a)));

#define CdrStreamKeyExt_t6a_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t6a_desc, (o))

typedef struct CdrStreamKeyExt_nested6b
{
  int32_t a;
} CdrStreamKeyExt_nested6b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_nested6b_desc;

#define CdrStreamKeyExt_nested6b__alloc() \
((CdrStreamKeyExt_nested6b*) dds_alloc (sizeof (CdrStreamKeyExt_nested6b)));

#define CdrStreamKeyExt_nested6b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_nested6b_desc, (o))

typedef struct CdrStreamKeyExt_t6b
{
  int32_t a;
  struct CdrStreamKeyExt_nested6b b;
} CdrStreamKeyExt_t6b;

extern const dds_topic_descriptor_t CdrStreamKeyExt_t6b_desc;

#define CdrStreamKeyExt_t6b__alloc() \
((CdrStreamKeyExt_t6b*) dds_alloc (sizeof (CdrStreamKeyExt_t6b)));

#define CdrStreamKeyExt_t6b_free(d,o) \
dds_sample_free ((d), &CdrStreamKeyExt_t6b_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CDRSTREAMKEYEXT_H_A8626E385FFB4A98197A9340F3D55976 */
