/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CreateWriter.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/CreateWriter.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_CREATEWRITER_H_65EDFDE082DB1159558F28C8F27A3AB6
#define DDSC_CREATEWRITER_H_65EDFDE082DB1159558F28C8F27A3AB6

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct DiscStress_CreateWriter_Msg
{
  int32_t round;
  uint32_t wrseq;
  uint32_t wridx;
  uint32_t histidx;
  uint32_t seq;
} DiscStress_CreateWriter_Msg;

extern const dds_topic_descriptor_t DiscStress_CreateWriter_Msg_desc;

#define DiscStress_CreateWriter_Msg__alloc() \
((DiscStress_CreateWriter_Msg*) dds_alloc (sizeof (DiscStress_CreateWriter_Msg)));

#define DiscStress_CreateWriter_Msg_free(d,o) \
dds_sample_free ((d), &DiscStress_CreateWriter_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CREATEWRITER_H_65EDFDE082DB1159558F28C8F27A3AB6 */
