/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: DataRepresentationTypes.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/DataRepresentationTypes.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_DATAREPRESENTATIONTYPES_H_981FD959E92DAB40359EAD15CADC2EB8
#define DDSC_DATAREPRESENTATIONTYPES_H_981FD959E92DAB40359EAD15CADC2EB8

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct DataRepresentationTypes_Subtype1
{
  char s1;
  int64_t s2;
  char s3;
} DataRepresentationTypes_Subtype1;

typedef struct DataRepresentationTypes_Type1
{
  struct DataRepresentationTypes_Subtype1 t1;
  char * t3;
  char t2;
} DataRepresentationTypes_Type1;

extern const dds_topic_descriptor_t DataRepresentationTypes_Type1_desc;

#define DataRepresentationTypes_Type1__alloc() \
((DataRepresentationTypes_Type1*) dds_alloc (sizeof (DataRepresentationTypes_Type1)));

#define DataRepresentationTypes_Type1_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_Type1_desc, (o))

typedef struct DataRepresentationTypes_Type2
{
  char t1[64];
  int32_t t2;
} DataRepresentationTypes_Type2;

extern const dds_topic_descriptor_t DataRepresentationTypes_Type2_desc;

#define DataRepresentationTypes_Type2__alloc() \
((DataRepresentationTypes_Type2*) dds_alloc (sizeof (DataRepresentationTypes_Type2)));

#define DataRepresentationTypes_Type2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_Type2_desc, (o))

typedef struct DataRepresentationTypes_Type3
{
  char t1;
  int64_t t2[10];
  int32_t t3;
} DataRepresentationTypes_Type3;

extern const dds_topic_descriptor_t DataRepresentationTypes_Type3_desc;

#define DataRepresentationTypes_Type3__alloc() \
((DataRepresentationTypes_Type3*) dds_alloc (sizeof (DataRepresentationTypes_Type3)));

#define DataRepresentationTypes_Type3_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_Type3_desc, (o))

typedef struct DataRepresentationTypes_TypeFinal
{
  int32_t a;
} DataRepresentationTypes_TypeFinal;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeFinal_desc;

#define DataRepresentationTypes_TypeFinal__alloc() \
((DataRepresentationTypes_TypeFinal*) dds_alloc (sizeof (DataRepresentationTypes_TypeFinal)));

#define DataRepresentationTypes_TypeFinal_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeFinal_desc, (o))

typedef struct DataRepresentationTypes_TypeAppendable
{
  int32_t a;
} DataRepresentationTypes_TypeAppendable;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeAppendable_desc;

#define DataRepresentationTypes_TypeAppendable__alloc() \
((DataRepresentationTypes_TypeAppendable*) dds_alloc (sizeof (DataRepresentationTypes_TypeAppendable)));

#define DataRepresentationTypes_TypeAppendable_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeAppendable_desc, (o))

typedef struct DataRepresentationTypes_TypeMutable
{
  int32_t a;
} DataRepresentationTypes_TypeMutable;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeMutable_desc;

#define DataRepresentationTypes_TypeMutable__alloc() \
((DataRepresentationTypes_TypeMutable*) dds_alloc (sizeof (DataRepresentationTypes_TypeMutable)));

#define DataRepresentationTypes_TypeMutable_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeMutable_desc, (o))

typedef struct DataRepresentationTypes_TypeNestedAppendable
{
  struct DataRepresentationTypes_TypeAppendable a;
} DataRepresentationTypes_TypeNestedAppendable;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeNestedAppendable_desc;

#define DataRepresentationTypes_TypeNestedAppendable__alloc() \
((DataRepresentationTypes_TypeNestedAppendable*) dds_alloc (sizeof (DataRepresentationTypes_TypeNestedAppendable)));

#define DataRepresentationTypes_TypeNestedAppendable_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeNestedAppendable_desc, (o))

typedef struct DataRepresentationTypes_TypeNestedMutable
{
  struct DataRepresentationTypes_TypeMutable a;
} DataRepresentationTypes_TypeNestedMutable;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeNestedMutable_desc;

#define DataRepresentationTypes_TypeNestedMutable__alloc() \
((DataRepresentationTypes_TypeNestedMutable*) dds_alloc (sizeof (DataRepresentationTypes_TypeNestedMutable)));

#define DataRepresentationTypes_TypeNestedMutable_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeNestedMutable_desc, (o))

typedef struct DataRepresentationTypes_TypeNestedMutableArr
{
  struct DataRepresentationTypes_TypeMutable a[5];
} DataRepresentationTypes_TypeNestedMutableArr;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeNestedMutableArr_desc;

#define DataRepresentationTypes_TypeNestedMutableArr__alloc() \
((DataRepresentationTypes_TypeNestedMutableArr*) dds_alloc (sizeof (DataRepresentationTypes_TypeNestedMutableArr)));

#define DataRepresentationTypes_TypeNestedMutableArr_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeNestedMutableArr_desc, (o))

#ifndef DDS_SEQUENCE_DATAREPRESENTATIONTYPES_TYPEMUTABLE_DEFINED
#define DDS_SEQUENCE_DATAREPRESENTATIONTYPES_TYPEMUTABLE_DEFINED
typedef struct dds_sequence_DataRepresentationTypes_TypeMutable
{
  uint32_t _maximum;
  uint32_t _length;
  struct DataRepresentationTypes_TypeMutable *_buffer;
  bool _release;
} dds_sequence_DataRepresentationTypes_TypeMutable;

#define dds_sequence_DataRepresentationTypes_TypeMutable__alloc() \
((dds_sequence_DataRepresentationTypes_TypeMutable*) dds_alloc (sizeof (dds_sequence_DataRepresentationTypes_TypeMutable)));

#define dds_sequence_DataRepresentationTypes_TypeMutable_allocbuf(l) \
((struct DataRepresentationTypes_TypeMutable *) dds_alloc ((l) * sizeof (struct DataRepresentationTypes_TypeMutable)))
#endif /* DDS_SEQUENCE_DATAREPRESENTATIONTYPES_TYPEMUTABLE_DEFINED */

typedef struct DataRepresentationTypes_TypeNestedMutableSeq
{
  dds_sequence_DataRepresentationTypes_TypeMutable a;
} DataRepresentationTypes_TypeNestedMutableSeq;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeNestedMutableSeq_desc;

#define DataRepresentationTypes_TypeNestedMutableSeq__alloc() \
((DataRepresentationTypes_TypeNestedMutableSeq*) dds_alloc (sizeof (DataRepresentationTypes_TypeNestedMutableSeq)));

#define DataRepresentationTypes_TypeNestedMutableSeq_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeNestedMutableSeq_desc, (o))

typedef struct DataRepresentationTypes_TypeNestedMutableUni
{
  int32_t _d;
  union
  {
    char a;
    struct DataRepresentationTypes_TypeNestedMutable b;
    int32_t c;
  } _u;
} DataRepresentationTypes_TypeNestedMutableUni;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeNestedMutableUni_desc;

#define DataRepresentationTypes_TypeNestedMutableUni__alloc() \
((DataRepresentationTypes_TypeNestedMutableUni*) dds_alloc (sizeof (DataRepresentationTypes_TypeNestedMutableUni)));

#define DataRepresentationTypes_TypeNestedMutableUni_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeNestedMutableUni_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr1
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr1;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr1_desc;

#define DataRepresentationTypes_TypeXcdr1__alloc() \
((DataRepresentationTypes_TypeXcdr1*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr1)));

#define DataRepresentationTypes_TypeXcdr1_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr1_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr2
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr2;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr2_desc;

#define DataRepresentationTypes_TypeXcdr2__alloc() \
((DataRepresentationTypes_TypeXcdr2*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr2)));

#define DataRepresentationTypes_TypeXcdr2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr2_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr1_2
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr1_2;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr1_2_desc;

#define DataRepresentationTypes_TypeXcdr1_2__alloc() \
((DataRepresentationTypes_TypeXcdr1_2*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr1_2)));

#define DataRepresentationTypes_TypeXcdr1_2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr1_2_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr1_xml_2
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr1_xml_2;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr1_xml_2_desc;

#define DataRepresentationTypes_TypeXcdr1_xml_2__alloc() \
((DataRepresentationTypes_TypeXcdr1_xml_2*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr1_xml_2)));

#define DataRepresentationTypes_TypeXcdr1_xml_2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr1_xml_2_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr1_other
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr1_other;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr1_other_desc;

#define DataRepresentationTypes_TypeXcdr1_other__alloc() \
((DataRepresentationTypes_TypeXcdr1_other*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr1_other)));

#define DataRepresentationTypes_TypeXcdr1_other_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr1_other_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdr2_other
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdr2_other;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdr2_other_desc;

#define DataRepresentationTypes_TypeXcdr2_other__alloc() \
((DataRepresentationTypes_TypeXcdr2_other*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdr2_other)));

#define DataRepresentationTypes_TypeXcdr2_other_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdr2_other_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdrA2
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdrA2;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdrA2_desc;

#define DataRepresentationTypes_TypeXcdrA2__alloc() \
((DataRepresentationTypes_TypeXcdrA2*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdrA2)));

#define DataRepresentationTypes_TypeXcdrA2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdrA2_desc, (o))

typedef struct DataRepresentationTypes_TypeXcdrA1_2
{
  int32_t f1;
} DataRepresentationTypes_TypeXcdrA1_2;

extern const dds_topic_descriptor_t DataRepresentationTypes_TypeXcdrA1_2_desc;

#define DataRepresentationTypes_TypeXcdrA1_2__alloc() \
((DataRepresentationTypes_TypeXcdrA1_2*) dds_alloc (sizeof (DataRepresentationTypes_TypeXcdrA1_2)));

#define DataRepresentationTypes_TypeXcdrA1_2_free(d,o) \
dds_sample_free ((d), &DataRepresentationTypes_TypeXcdrA1_2_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DATAREPRESENTATIONTYPES_H_981FD959E92DAB40359EAD15CADC2EB8 */
