/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: InstanceHandleTypes.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/InstanceHandleTypes.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_INSTANCEHANDLETYPES_H_EB8FA441039FDD667760B5CAD56658B8
#define DDSC_INSTANCEHANDLETYPES_H_EB8FA441039FDD667760B5CAD56658B8

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct InstanceHandleTypes_A
{
  uint32_t k;
  uint32_t v;
} InstanceHandleTypes_A;

extern const dds_topic_descriptor_t InstanceHandleTypes_A_desc;

#define InstanceHandleTypes_A__alloc() \
((InstanceHandleTypes_A*) dds_alloc (sizeof (InstanceHandleTypes_A)));

#define InstanceHandleTypes_A_free(d,o) \
dds_sample_free ((d), &InstanceHandleTypes_A_desc, (o))

typedef struct InstanceHandleTypes_C
{
  uint32_t k;
  uint32_t v;
} InstanceHandleTypes_C;

extern const dds_topic_descriptor_t InstanceHandleTypes_C_desc;

#define InstanceHandleTypes_C__alloc() \
((InstanceHandleTypes_C*) dds_alloc (sizeof (InstanceHandleTypes_C)));

#define InstanceHandleTypes_C_free(d,o) \
dds_sample_free ((d), &InstanceHandleTypes_C_desc, (o))

typedef struct InstanceHandleTypes_MD5
{
  uint8_t k[128];
} InstanceHandleTypes_MD5;

extern const dds_topic_descriptor_t InstanceHandleTypes_MD5_desc;

#define InstanceHandleTypes_MD5__alloc() \
((InstanceHandleTypes_MD5*) dds_alloc (sizeof (InstanceHandleTypes_MD5)));

#define InstanceHandleTypes_MD5_free(d,o) \
dds_sample_free ((d), &InstanceHandleTypes_MD5_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_INSTANCEHANDLETYPES_H_EB8FA441039FDD667760B5CAD56658B8 */
