/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: PsmxDataModels.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/PsmxDataModels.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_PSMXDATAMODELS_H_CD204B52E0A32950EB9B604774538B38
#define DDSC_PSMXDATAMODELS_H_CD204B52E0A32950EB9B604774538B38

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct SC_Model
{
  uint8_t a;
  uint8_t b;
  uint8_t c;
} SC_Model;

extern const dds_topic_descriptor_t SC_Model_desc;

#define SC_Model__alloc() \
((SC_Model*) dds_alloc (sizeof (SC_Model)));

#define SC_Model_free(d,o) \
dds_sample_free ((d), &SC_Model_desc, (o))

typedef struct NSC_Model
{
  char * a;
  char * b;
  char * c;
} NSC_Model;

extern const dds_topic_descriptor_t NSC_Model_desc;

#define NSC_Model__alloc() \
((NSC_Model*) dds_alloc (sizeof (NSC_Model)));

#define NSC_Model_free(d,o) \
dds_sample_free ((d), &NSC_Model_desc, (o))

typedef struct PsmxType1xy
{
  int32_t x;
  uint8_t y;
} PsmxType1xy;

typedef struct PsmxType1
{
  struct PsmxType1xy xy;
  uint8_t z;
} PsmxType1;

extern const dds_topic_descriptor_t PsmxType1_desc;

#define PsmxType1__alloc() \
((PsmxType1*) dds_alloc (sizeof (PsmxType1)));

#define PsmxType1_free(d,o) \
dds_sample_free ((d), &PsmxType1_desc, (o))

typedef struct PsmxKeySupportCheck
{
  int32_t k;
} PsmxKeySupportCheck;

extern const dds_topic_descriptor_t PsmxKeySupportCheck_desc;

#define PsmxKeySupportCheck__alloc() \
((PsmxKeySupportCheck*) dds_alloc (sizeof (PsmxKeySupportCheck)));

#define PsmxKeySupportCheck_free(d,o) \
dds_sample_free ((d), &PsmxKeySupportCheck_desc, (o))

typedef struct PsmxLoanTest0
{
  struct PsmxType1xy xy;
  uint8_t z;
} PsmxLoanTest0;

extern const dds_topic_descriptor_t PsmxLoanTest0_desc;

#define PsmxLoanTest0__alloc() \
((PsmxLoanTest0*) dds_alloc (sizeof (PsmxLoanTest0)));

#define PsmxLoanTest0_free(d,o) \
dds_sample_free ((d), &PsmxLoanTest0_desc, (o))

typedef struct PsmxLoanTest1
{
  struct PsmxType1xy xy;
  uint8_t z;
  char * str;
} PsmxLoanTest1;

extern const dds_topic_descriptor_t PsmxLoanTest1_desc;

#define PsmxLoanTest1__alloc() \
((PsmxLoanTest1*) dds_alloc (sizeof (PsmxLoanTest1)));

#define PsmxLoanTest1_free(d,o) \
dds_sample_free ((d), &PsmxLoanTest1_desc, (o))

typedef struct PsmxLoanTest2
{
  struct PsmxType1xy xy;
  uint8_t z;
  char * str;
} PsmxLoanTest2;

extern const dds_topic_descriptor_t PsmxLoanTest2_desc;

#define PsmxLoanTest2__alloc() \
((PsmxLoanTest2*) dds_alloc (sizeof (PsmxLoanTest2)));

#define PsmxLoanTest2_free(d,o) \
dds_sample_free ((d), &PsmxLoanTest2_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PSMXDATAMODELS_H_CD204B52E0A32950EB9B604774538B38 */
