/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: psmx_cdds_data.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/psmx_cdds_data.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_PSMX_CDDS_DATA_H_0A5968457188D473A98C1D3AED7B6CE6
#define DDSC_PSMX_CDDS_DATA_H_0A5968457188D473A98C1D3AED7B6CE6

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum sample_state
{
  SAMPLE_STATE_UNITIALIZED,
  SAMPLE_STATE_RAW_KEY,
  SAMPLE_STATE_RAW_DATA,
  SAMPLE_STATE_SERIALIZED_KEY,
  SAMPLE_STATE_SERIALIZED_DATA
} sample_state;

#define sample_state__alloc() \
((sample_state*) dds_alloc (sizeof (sample_state)));

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct cdds_psmx_data
{
  sample_state sample_state;
  uint32_t data_type;
  uint32_t psmx_instance_id;
  uint32_t sample_size;
  uint8_t guid[16];
  int64_t timestamp;
  uint32_t statusinfo;
  uint16_t cdr_identifier;
  uint16_t cdr_options;
  dds_sequence_octet data;
} cdds_psmx_data;

extern const dds_topic_descriptor_t cdds_psmx_data_desc;

#define cdds_psmx_data__alloc() \
((cdds_psmx_data*) dds_alloc (sizeof (cdds_psmx_data)));

#define cdds_psmx_data_free(d,o) \
dds_sample_free ((d), &cdds_psmx_data_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_PSMX_CDDS_DATA_H_0A5968457188D473A98C1D3AED7B6CE6 */
