/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RoundTrip.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/RoundTrip.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_ROUNDTRIP_H_22F83D8EDCD6C3E6817D4AC918C94B71
#define DDSC_ROUNDTRIP_H_22F83D8EDCD6C3E6817D4AC918C94B71

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct RoundTripModule_DataType
{
  dds_sequence_octet payload;
} RoundTripModule_DataType;

extern const dds_topic_descriptor_t RoundTripModule_DataType_desc;

#define RoundTripModule_DataType__alloc() \
((RoundTripModule_DataType*) dds_alloc (sizeof (RoundTripModule_DataType)));

#define RoundTripModule_DataType_free(d,o) \
dds_sample_free ((d), &RoundTripModule_DataType_desc, (o))

typedef struct RoundTripModule_Address
{
  char * ip;
  int32_t port;
} RoundTripModule_Address;

extern const dds_topic_descriptor_t RoundTripModule_Address_desc;

#define RoundTripModule_Address__alloc() \
((RoundTripModule_Address*) dds_alloc (sizeof (RoundTripModule_Address)));

#define RoundTripModule_Address_free(d,o) \
dds_sample_free ((d), &RoundTripModule_Address_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_ROUNDTRIP_H_22F83D8EDCD6C3E6817D4AC918C94B71 */
