/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: TypesArrayKey.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/TypesArrayKey.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_TYPESARRAYKEY_H_C9D0B7A1B404284FED5572A8E39AD472
#define DDSC_TYPESARRAYKEY_H_C9D0B7A1B404284FED5572A8E39AD472

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct TypesArrayKey_long_arraytypekey
{
  int32_t key[20];
} TypesArrayKey_long_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_long_arraytypekey_desc;

#define TypesArrayKey_long_arraytypekey__alloc() \
((TypesArrayKey_long_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_long_arraytypekey)));

#define TypesArrayKey_long_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_long_arraytypekey_desc, (o))

typedef int64_t TypesArrayKey_longlong;

#define TypesArrayKey_longlong__alloc() \
((TypesArrayKey_longlong*) dds_alloc (sizeof (TypesArrayKey_longlong)));

typedef struct TypesArrayKey_longlong_arraytypekey
{
  TypesArrayKey_longlong key[20];
} TypesArrayKey_longlong_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_longlong_arraytypekey_desc;

#define TypesArrayKey_longlong_arraytypekey__alloc() \
((TypesArrayKey_longlong_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_longlong_arraytypekey)));

#define TypesArrayKey_longlong_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_longlong_arraytypekey_desc, (o))

typedef uint16_t TypesArrayKey_unsignedshort;

#define TypesArrayKey_unsignedshort__alloc() \
((TypesArrayKey_unsignedshort*) dds_alloc (sizeof (TypesArrayKey_unsignedshort)));

typedef struct TypesArrayKey_unsignedshort_arraytypekey
{
  TypesArrayKey_unsignedshort key[20];
} TypesArrayKey_unsignedshort_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_unsignedshort_arraytypekey_desc;

#define TypesArrayKey_unsignedshort_arraytypekey__alloc() \
((TypesArrayKey_unsignedshort_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_unsignedshort_arraytypekey)));

#define TypesArrayKey_unsignedshort_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_unsignedshort_arraytypekey_desc, (o))

typedef uint32_t TypesArrayKey_unsignedlong;

#define TypesArrayKey_unsignedlong__alloc() \
((TypesArrayKey_unsignedlong*) dds_alloc (sizeof (TypesArrayKey_unsignedlong)));

typedef struct TypesArrayKey_unsignedlong_arraytypekey
{
  TypesArrayKey_unsignedlong key[20];
} TypesArrayKey_unsignedlong_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_unsignedlong_arraytypekey_desc;

#define TypesArrayKey_unsignedlong_arraytypekey__alloc() \
((TypesArrayKey_unsignedlong_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_unsignedlong_arraytypekey)));

#define TypesArrayKey_unsignedlong_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_unsignedlong_arraytypekey_desc, (o))

typedef uint64_t TypesArrayKey_unsignedlonglong;

#define TypesArrayKey_unsignedlonglong__alloc() \
((TypesArrayKey_unsignedlonglong*) dds_alloc (sizeof (TypesArrayKey_unsignedlonglong)));

typedef struct TypesArrayKey_unsignedlonglong_arraytypekey
{
  TypesArrayKey_unsignedlonglong key[20];
} TypesArrayKey_unsignedlonglong_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_unsignedlonglong_arraytypekey_desc;

#define TypesArrayKey_unsignedlonglong_arraytypekey__alloc() \
((TypesArrayKey_unsignedlonglong_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_unsignedlonglong_arraytypekey)));

#define TypesArrayKey_unsignedlonglong_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_unsignedlonglong_arraytypekey_desc, (o))

typedef struct TypesArrayKey_float_arraytypekey
{
  float key[20];
} TypesArrayKey_float_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_float_arraytypekey_desc;

#define TypesArrayKey_float_arraytypekey__alloc() \
((TypesArrayKey_float_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_float_arraytypekey)));

#define TypesArrayKey_float_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_float_arraytypekey_desc, (o))

typedef struct TypesArrayKey_double_arraytypekey
{
  double key[20];
} TypesArrayKey_double_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_double_arraytypekey_desc;

#define TypesArrayKey_double_arraytypekey__alloc() \
((TypesArrayKey_double_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_double_arraytypekey)));

#define TypesArrayKey_double_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_double_arraytypekey_desc, (o))

typedef struct TypesArrayKey_char_arraytypekey
{
  char key[128];
} TypesArrayKey_char_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_char_arraytypekey_desc;

#define TypesArrayKey_char_arraytypekey__alloc() \
((TypesArrayKey_char_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_char_arraytypekey)));

#define TypesArrayKey_char_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_char_arraytypekey_desc, (o))

typedef struct TypesArrayKey_boolean_arraytypekey
{
  bool key[128];
} TypesArrayKey_boolean_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_boolean_arraytypekey_desc;

#define TypesArrayKey_boolean_arraytypekey__alloc() \
((TypesArrayKey_boolean_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_boolean_arraytypekey)));

#define TypesArrayKey_boolean_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_boolean_arraytypekey_desc, (o))

typedef struct TypesArrayKey_octet_arraytypekey
{
  uint8_t key[128];
} TypesArrayKey_octet_arraytypekey;

extern const dds_topic_descriptor_t TypesArrayKey_octet_arraytypekey_desc;

#define TypesArrayKey_octet_arraytypekey__alloc() \
((TypesArrayKey_octet_arraytypekey*) dds_alloc (sizeof (TypesArrayKey_octet_arraytypekey)));

#define TypesArrayKey_octet_arraytypekey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_octet_arraytypekey_desc, (o))

typedef struct TypesArrayKey_alltypeskey
{
  int32_t l;
  int64_t ll;
  uint16_t us;
  uint32_t ul;
  uint64_t ull;
  float f;
  double d;
  char c;
  bool b;
  uint8_t o;
  char * s;
} TypesArrayKey_alltypeskey;

extern const dds_topic_descriptor_t TypesArrayKey_alltypeskey_desc;

#define TypesArrayKey_alltypeskey__alloc() \
((TypesArrayKey_alltypeskey*) dds_alloc (sizeof (TypesArrayKey_alltypeskey)));

#define TypesArrayKey_alltypeskey_free(d,o) \
dds_sample_free ((d), &TypesArrayKey_alltypeskey_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TYPESARRAYKEY_H_C9D0B7A1B404284FED5572A8E39AD472 */
