/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: TypeBuilderTypes.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/TypeBuilderTypes.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_TYPEBUILDERTYPES_H_29B1475AF9AD2FF9D7ADF607B4C3EF8F
#define DDSC_TYPEBUILDERTYPES_H_29B1475AF9AD2FF9D7ADF607B4C3EF8F

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum TypeBuilderTypes_en
{
  TypeBuilderTypes_E1,
  TypeBuilderTypes_E2
} TypeBuilderTypes_en;

#define TypeBuilderTypes_en__alloc() \
((TypeBuilderTypes_en*) dds_alloc (sizeof (TypeBuilderTypes_en)));

typedef uint32_t TypeBuilderTypes_bm;
#define TypeBuilderTypes_BM1 (1lu << 0)
#define TypeBuilderTypes_BM2 (1lu << 1)
typedef struct TypeBuilderTypes_t1
{
  int32_t f1;
} TypeBuilderTypes_t1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t1_desc;

#define TypeBuilderTypes_t1__alloc() \
((TypeBuilderTypes_t1*) dds_alloc (sizeof (TypeBuilderTypes_t1)));

#define TypeBuilderTypes_t1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t1_desc, (o))

typedef struct TypeBuilderTypes_t2
{
  uint8_t f1;
  char f2;
  uint16_t f3;
  int16_t * f4;
  uint32_t f5;
  int32_t f6;
  uint64_t * f7;
  int64_t f8;
  bool f9;
  char * f10;
  char f11[11];
  TypeBuilderTypes_en * f12;
  TypeBuilderTypes_bm f13;
} TypeBuilderTypes_t2;

extern const dds_topic_descriptor_t TypeBuilderTypes_t2_desc;

#define TypeBuilderTypes_t2__alloc() \
((TypeBuilderTypes_t2*) dds_alloc (sizeof (TypeBuilderTypes_t2)));

#define TypeBuilderTypes_t2_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t2_desc, (o))

typedef struct TypeBuilderTypes_t3a
{
  int16_t f1;
} TypeBuilderTypes_t3a;

extern const dds_topic_descriptor_t TypeBuilderTypes_t3a_desc;

#define TypeBuilderTypes_t3a__alloc() \
((TypeBuilderTypes_t3a*) dds_alloc (sizeof (TypeBuilderTypes_t3a)));

#define TypeBuilderTypes_t3a_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t3a_desc, (o))

typedef struct TypeBuilderTypes_t3
{
  struct TypeBuilderTypes_t1 f1;
  struct TypeBuilderTypes_t3a f2;
  struct TypeBuilderTypes_t2 f3;
} TypeBuilderTypes_t3;

extern const dds_topic_descriptor_t TypeBuilderTypes_t3_desc;

#define TypeBuilderTypes_t3__alloc() \
((TypeBuilderTypes_t3*) dds_alloc (sizeof (TypeBuilderTypes_t3)));

#define TypeBuilderTypes_t3_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t3_desc, (o))

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t1
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t1;

#define dds_sequence_TypeBuilderTypes_t1__alloc() \
((dds_sequence_TypeBuilderTypes_t1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t1)));

#define dds_sequence_TypeBuilderTypes_t1_allocbuf(l) \
((struct TypeBuilderTypes_t1 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T1_DEFINED */

typedef struct TypeBuilderTypes_t4
{
  dds_sequence_long f1;
  dds_sequence_string f2;
  dds_sequence_TypeBuilderTypes_t1 f3;
} TypeBuilderTypes_t4;

extern const dds_topic_descriptor_t TypeBuilderTypes_t4_desc;

#define TypeBuilderTypes_t4__alloc() \
((TypeBuilderTypes_t4*) dds_alloc (sizeof (TypeBuilderTypes_t4)));

#define TypeBuilderTypes_t4_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t4_desc, (o))

typedef struct TypeBuilderTypes_td1
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} TypeBuilderTypes_td1;

#define TypeBuilderTypes_td1__alloc() \
((TypeBuilderTypes_td1*) dds_alloc (sizeof (TypeBuilderTypes_td1)));

#define TypeBuilderTypes_td1_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
typedef int32_t TypeBuilderTypes_tda1[2];

#define TypeBuilderTypes_tda1__alloc() \
((TypeBuilderTypes_tda1*) dds_alloc (sizeof (TypeBuilderTypes_tda1)));

typedef TypeBuilderTypes_tda1 TypeBuilderTypes_tda2;

#define TypeBuilderTypes_tda2__alloc() \
((TypeBuilderTypes_tda2*) dds_alloc (sizeof (TypeBuilderTypes_tda2)));

typedef TypeBuilderTypes_td1 TypeBuilderTypes_tda3;

#define TypeBuilderTypes_tda3__alloc() \
((TypeBuilderTypes_tda3*) dds_alloc (sizeof (TypeBuilderTypes_tda3)));

typedef TypeBuilderTypes_tda3 TypeBuilderTypes_tda4[6];

#define TypeBuilderTypes_tda4__alloc() \
((TypeBuilderTypes_tda4*) dds_alloc (sizeof (TypeBuilderTypes_tda4)));

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_tda4
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_tda4 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_tda4;

#define dds_sequence_TypeBuilderTypes_tda4__alloc() \
((dds_sequence_TypeBuilderTypes_tda4*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_tda4)));

#define dds_sequence_TypeBuilderTypes_tda4_allocbuf(l) \
((TypeBuilderTypes_tda4 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_tda4)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_tda4
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_tda4 *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_tda4;

#define dds_sequence_sequence_TypeBuilderTypes_tda4__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_tda4*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_tda4)));

#define dds_sequence_sequence_TypeBuilderTypes_tda4_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_tda4 *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_tda4)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA4_DEFINED */

typedef struct TypeBuilderTypes_td2
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_sequence_TypeBuilderTypes_tda4 *_buffer;
  bool _release;
} TypeBuilderTypes_td2;

#define TypeBuilderTypes_td2__alloc() \
((TypeBuilderTypes_td2*) dds_alloc (sizeof (TypeBuilderTypes_td2)));

#define TypeBuilderTypes_td2_allocbuf(l) \
((dds_sequence_sequence_TypeBuilderTypes_tda4 *) dds_alloc ((l) * sizeof (dds_sequence_sequence_TypeBuilderTypes_tda4)))
typedef struct TypeBuilderTypes_temp
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} TypeBuilderTypes_temp;

#define TypeBuilderTypes_temp__alloc() \
((TypeBuilderTypes_temp*) dds_alloc (sizeof (TypeBuilderTypes_temp)));

#define TypeBuilderTypes_temp_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
typedef enum TypeBuilderTypes_en8
{
  TypeBuilderTypes_EN8_1,
  TypeBuilderTypes_EN8_2
} TypeBuilderTypes_en8;

#define TypeBuilderTypes_en8__alloc() \
((TypeBuilderTypes_en8*) dds_alloc (sizeof (TypeBuilderTypes_en8)));

typedef uint16_t TypeBuilderTypes_bm16;
#define TypeBuilderTypes_BM16_1 (1 << 0)
#define TypeBuilderTypes_BM16_2 (1 << 1)
#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_long *_buffer;
  bool _release;
} dds_sequence_sequence_long;

#define dds_sequence_sequence_long__alloc() \
((dds_sequence_sequence_long*) dds_alloc (sizeof (dds_sequence_sequence_long)));

#define dds_sequence_sequence_long_allocbuf(l) \
((dds_sequence_long *) dds_alloc ((l) * sizeof (dds_sequence_long)))
#endif /* DDS_SEQUENCE_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_bm16
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_bm16 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_bm16;

#define dds_sequence_TypeBuilderTypes_bm16__alloc() \
((dds_sequence_TypeBuilderTypes_bm16*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_bm16)));

#define dds_sequence_TypeBuilderTypes_bm16_allocbuf(l) \
((TypeBuilderTypes_bm16 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_bm16)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_bm16
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_bm16 *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_bm16;

#define dds_sequence_sequence_TypeBuilderTypes_bm16__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_bm16*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_bm16)));

#define dds_sequence_sequence_TypeBuilderTypes_bm16_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_bm16 *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_bm16)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TD1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TD1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_td1
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_td1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_td1;

#define dds_sequence_TypeBuilderTypes_td1__alloc() \
((dds_sequence_TypeBuilderTypes_td1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_td1)));

#define dds_sequence_TypeBuilderTypes_td1_allocbuf(l) \
((TypeBuilderTypes_td1 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_td1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TD1_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_td2
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_td2 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_td2;

#define dds_sequence_TypeBuilderTypes_td2__alloc() \
((dds_sequence_TypeBuilderTypes_td2*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_td2)));

#define dds_sequence_TypeBuilderTypes_td2_allocbuf(l) \
((TypeBuilderTypes_td2 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_td2)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_td2
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_td2 *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_td2;

#define dds_sequence_sequence_TypeBuilderTypes_td2__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_td2*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_td2)));

#define dds_sequence_sequence_TypeBuilderTypes_td2_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_td2 *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_td2)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_bm16
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_bm16 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_bm16;

#define dds_sequence_TypeBuilderTypes_bm16__alloc() \
((dds_sequence_TypeBuilderTypes_bm16*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_bm16)));

#define dds_sequence_TypeBuilderTypes_bm16_allocbuf(l) \
((TypeBuilderTypes_bm16 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_bm16)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_bm16
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_bm16 *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_bm16;

#define dds_sequence_sequence_TypeBuilderTypes_bm16__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_bm16*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_bm16)));

#define dds_sequence_sequence_TypeBuilderTypes_bm16_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_bm16 *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_bm16)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_BM16_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_tda1
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_tda1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_tda1;

#define dds_sequence_TypeBuilderTypes_tda1__alloc() \
((dds_sequence_TypeBuilderTypes_tda1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_tda1)));

#define dds_sequence_TypeBuilderTypes_tda1_allocbuf(l) \
((TypeBuilderTypes_tda1 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_tda1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_tda1
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_tda1 *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_tda1;

#define dds_sequence_sequence_TypeBuilderTypes_tda1__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_tda1*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_tda1)));

#define dds_sequence_sequence_TypeBuilderTypes_tda1_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_tda1 *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_tda1)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_TDA1_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TDA2_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TDA2_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_tda2
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_tda2 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_tda2;

#define dds_sequence_TypeBuilderTypes_tda2__alloc() \
((dds_sequence_TypeBuilderTypes_tda2*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_tda2)));

#define dds_sequence_TypeBuilderTypes_tda2_allocbuf(l) \
((TypeBuilderTypes_tda2 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_tda2)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TDA2_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TDA3_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TDA3_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_tda3
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_tda3 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_tda3;

#define dds_sequence_TypeBuilderTypes_tda3__alloc() \
((dds_sequence_TypeBuilderTypes_tda3*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_tda3)));

#define dds_sequence_TypeBuilderTypes_tda3_allocbuf(l) \
((TypeBuilderTypes_tda3 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_tda3)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TDA3_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_td2
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_td2 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_td2;

#define dds_sequence_TypeBuilderTypes_td2__alloc() \
((dds_sequence_TypeBuilderTypes_td2*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_td2)));

#define dds_sequence_TypeBuilderTypes_td2_allocbuf(l) \
((TypeBuilderTypes_td2 *) dds_alloc ((l) * sizeof (TypeBuilderTypes_td2)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_TD2_DEFINED */

typedef struct TypeBuilderTypes_t5
{
  int16_t _d;
  union
  {
    char u1;
    int32_t u2;
    char u3[6];
    int32_t u4;
    struct TypeBuilderTypes_t1 u6;
    TypeBuilderTypes_bm u8;
    dds_sequence_long u9;
    dds_sequence_long u10;
    char * u11;
    TypeBuilderTypes_en u12;
    int32_t * u13;
    char * u14;
    struct TypeBuilderTypes_t1 * u15;
    bool u17;
    float u18;
    TypeBuilderTypes_en8 u19;
    TypeBuilderTypes_bm16 u21;
    TypeBuilderTypes_td1 u22;
    dds_sequence_long (* u23)[3];
    dds_sequence_sequence_long (* u24)[3];
    dds_sequence_sequence_TypeBuilderTypes_bm16 (* u25)[3][4];
    dds_sequence_TypeBuilderTypes_td1 (* u26)[3];
    dds_sequence_sequence_TypeBuilderTypes_td2 (* u27)[500][50][5];
    dds_sequence_sequence_TypeBuilderTypes_bm16 u28[3][4];
    dds_sequence_sequence_TypeBuilderTypes_tda1 u29[3][4];
    dds_sequence_TypeBuilderTypes_tda2 u30[300][4];
    dds_sequence_TypeBuilderTypes_tda3 u31[3][400];
    TypeBuilderTypes_tda4 u32[400][500];
    dds_sequence_TypeBuilderTypes_td2 u33[500];
    TypeBuilderTypes_temp u34;
    struct TypeBuilderTypes_t4 u35;
  } _u;
} TypeBuilderTypes_t5;

extern const dds_topic_descriptor_t TypeBuilderTypes_t5_desc;

#define TypeBuilderTypes_t5__alloc() \
((TypeBuilderTypes_t5*) dds_alloc (sizeof (TypeBuilderTypes_t5)));

#define TypeBuilderTypes_t5_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t5_desc, (o))

typedef int32_t TypeBuilderTypes_arr_def[300];

#define TypeBuilderTypes_arr_def__alloc() \
((TypeBuilderTypes_arr_def*) dds_alloc (sizeof (TypeBuilderTypes_arr_def)));

typedef TypeBuilderTypes_arr_def TypeBuilderTypes_arr_def2[300];

#define TypeBuilderTypes_arr_def2__alloc() \
((TypeBuilderTypes_arr_def2*) dds_alloc (sizeof (TypeBuilderTypes_arr_def2)));

typedef struct TypeBuilderTypes_seq_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_arr_def *_buffer;
  bool _release;
} TypeBuilderTypes_seq_def;

#define TypeBuilderTypes_seq_def__alloc() \
((TypeBuilderTypes_seq_def*) dds_alloc (sizeof (TypeBuilderTypes_seq_def)));

#define TypeBuilderTypes_seq_def_allocbuf(l) \
((TypeBuilderTypes_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_arr_def)))
typedef struct TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_arr_def *_buffer;
  bool _release;
} TypeBuilderTypes_seq_arr_def [2];

#define TypeBuilderTypes_seq_arr_def__alloc() \
((TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (TypeBuilderTypes_seq_arr_def)));

#define TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((TypeBuilderTypes_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_arr_def)))
#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_ARR_DEF_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_ARR_DEF_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_arr_def *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_arr_def;

#define dds_sequence_TypeBuilderTypes_arr_def__alloc() \
((dds_sequence_TypeBuilderTypes_arr_def*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_arr_def)));

#define dds_sequence_TypeBuilderTypes_arr_def_allocbuf(l) \
((TypeBuilderTypes_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_arr_def)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_ARR_DEF_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_DEF_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_DEF_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_seq_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_seq_def *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_seq_def;

#define dds_sequence_TypeBuilderTypes_seq_def__alloc() \
((dds_sequence_TypeBuilderTypes_seq_def*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_seq_def)));

#define dds_sequence_TypeBuilderTypes_seq_def_allocbuf(l) \
((TypeBuilderTypes_seq_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_seq_def)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_DEF_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_seq_arr_def *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_seq_arr_def;

#define dds_sequence_TypeBuilderTypes_seq_arr_def__alloc() \
((dds_sequence_TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_seq_arr_def)));

#define dds_sequence_TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((TypeBuilderTypes_seq_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_seq_arr_def)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_seq_arr_def *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_seq_arr_def;

#define dds_sequence_TypeBuilderTypes_seq_arr_def__alloc() \
((dds_sequence_TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_seq_arr_def)));

#define dds_sequence_TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((TypeBuilderTypes_seq_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_seq_arr_def)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  TypeBuilderTypes_seq_arr_def *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_seq_arr_def;

#define dds_sequence_TypeBuilderTypes_seq_arr_def__alloc() \
((dds_sequence_TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_seq_arr_def)));

#define dds_sequence_TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((TypeBuilderTypes_seq_arr_def *) dds_alloc ((l) * sizeof (TypeBuilderTypes_seq_arr_def)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_seq_arr_def *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_seq_arr_def;

#define dds_sequence_sequence_TypeBuilderTypes_seq_arr_def__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_seq_arr_def)));

#define dds_sequence_sequence_TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_seq_arr_def *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_seq_arr_def)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
#define DDS_SEQUENCE_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED
typedef struct dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_sequence_TypeBuilderTypes_seq_arr_def *_buffer;
  bool _release;
} dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def;

#define dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def__alloc() \
((dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def*) dds_alloc (sizeof (dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def)));

#define dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def_allocbuf(l) \
((dds_sequence_sequence_TypeBuilderTypes_seq_arr_def *) dds_alloc ((l) * sizeof (dds_sequence_sequence_TypeBuilderTypes_seq_arr_def)))
#endif /* DDS_SEQUENCE_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_SEQ_ARR_DEF_DEFINED */

typedef struct TypeBuilderTypes_t6
{
  int32_t f1[2];
  char f2[1000];
  struct TypeBuilderTypes_t1 f3[3];
  TypeBuilderTypes_en f4[15];
  TypeBuilderTypes_en8 f5[1];
  TypeBuilderTypes_bm f6[10];
  TypeBuilderTypes_bm16 f7[100];
  int32_t (* f8)[2];
  dds_sequence_long f9[10];
  TypeBuilderTypes_arr_def f10;
  TypeBuilderTypes_arr_def f11[3];
  TypeBuilderTypes_arr_def2 f12;
  TypeBuilderTypes_arr_def2 f13[6];
  TypeBuilderTypes_seq_def f14;
  TypeBuilderTypes_seq_def f15[5];
  TypeBuilderTypes_seq_arr_def f16;
  TypeBuilderTypes_seq_arr_def f17[10];
  dds_sequence_TypeBuilderTypes_arr_def f18;
  dds_sequence_TypeBuilderTypes_seq_def f19;
  dds_sequence_TypeBuilderTypes_seq_arr_def f20;
  dds_sequence_TypeBuilderTypes_seq_arr_def f21[3];
  dds_sequence_sequence_sequence_TypeBuilderTypes_seq_arr_def f22[3][4];
} TypeBuilderTypes_t6;

extern const dds_topic_descriptor_t TypeBuilderTypes_t6_desc;

#define TypeBuilderTypes_t6__alloc() \
((TypeBuilderTypes_t6*) dds_alloc (sizeof (TypeBuilderTypes_t6)));

#define TypeBuilderTypes_t6_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t6_desc, (o))

typedef struct TypeBuilderTypes_tk1
{
  int32_t tk1_1;
  int32_t tk1_2;
} TypeBuilderTypes_tk1;

typedef struct TypeBuilderTypes_tk2
{
  int32_t tk2_1;
  int32_t tk2_2;
} TypeBuilderTypes_tk2;

typedef struct TypeBuilderTypes_tk3n
{
  int32_t tk3n_1;
} TypeBuilderTypes_tk3n;

typedef struct TypeBuilderTypes_tk3
{
  int32_t tk3_1;
  struct TypeBuilderTypes_tk3n tk3_2;
} TypeBuilderTypes_tk3;

typedef struct TypeBuilderTypes_t7
{
  int32_t f1;
  struct TypeBuilderTypes_tk1 f2;
  struct TypeBuilderTypes_tk2 f3;
  int32_t f4;
  struct TypeBuilderTypes_tk3 f5;
} TypeBuilderTypes_t7;

extern const dds_topic_descriptor_t TypeBuilderTypes_t7_desc;

#define TypeBuilderTypes_t7__alloc() \
((TypeBuilderTypes_t7*) dds_alloc (sizeof (TypeBuilderTypes_t7)));

#define TypeBuilderTypes_t7_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t7_desc, (o))

typedef struct TypeBuilderTypes_t8
{
  char f1;
  TypeBuilderTypes_bm f2;
  TypeBuilderTypes_bm f3;
  char f4;
  char f5;
  TypeBuilderTypes_en f6;
  TypeBuilderTypes_en f7;
} TypeBuilderTypes_t8;

extern const dds_topic_descriptor_t TypeBuilderTypes_t8_desc;

#define TypeBuilderTypes_t8__alloc() \
((TypeBuilderTypes_t8*) dds_alloc (sizeof (TypeBuilderTypes_t8)));

#define TypeBuilderTypes_t8_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t8_desc, (o))

typedef struct TypeBuilderTypes_t9
{
  int32_t * f1;
  struct TypeBuilderTypes_t8 * f2;
  struct TypeBuilderTypes_t5 * f3;
  struct TypeBuilderTypes_t7 * f4;
} TypeBuilderTypes_t9;

extern const dds_topic_descriptor_t TypeBuilderTypes_t9_desc;

#define TypeBuilderTypes_t9__alloc() \
((TypeBuilderTypes_t9*) dds_alloc (sizeof (TypeBuilderTypes_t9)));

#define TypeBuilderTypes_t9_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t9_desc, (o))

typedef struct TypeBuilderTypes_t10_2
{
  int32_t f10_2;
} TypeBuilderTypes_t10_2;

extern const dds_topic_descriptor_t TypeBuilderTypes_t10_2_desc;

#define TypeBuilderTypes_t10_2__alloc() \
((TypeBuilderTypes_t10_2*) dds_alloc (sizeof (TypeBuilderTypes_t10_2)));

#define TypeBuilderTypes_t10_2_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t10_2_desc, (o))

typedef struct TypeBuilderTypes_t10_1
{
  struct TypeBuilderTypes_t10_2 parent;
  int32_t f10_1;
} TypeBuilderTypes_t10_1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t10_1_desc;

#define TypeBuilderTypes_t10_1__alloc() \
((TypeBuilderTypes_t10_1*) dds_alloc (sizeof (TypeBuilderTypes_t10_1)));

#define TypeBuilderTypes_t10_1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t10_1_desc, (o))

typedef struct TypeBuilderTypes_t10
{
  struct TypeBuilderTypes_t10_1 parent;
  int32_t f1;
  struct TypeBuilderTypes_t10_2 f2;
} TypeBuilderTypes_t10;

extern const dds_topic_descriptor_t TypeBuilderTypes_t10_desc;

#define TypeBuilderTypes_t10__alloc() \
((TypeBuilderTypes_t10*) dds_alloc (sizeof (TypeBuilderTypes_t10)));

#define TypeBuilderTypes_t10_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t10_desc, (o))

typedef struct TypeBuilderTypes_t11a
{
  int32_t f1;
} TypeBuilderTypes_t11a;

typedef struct TypeBuilderTypes_t11b
{
  struct TypeBuilderTypes_t11a f1;
} TypeBuilderTypes_t11b;

typedef struct TypeBuilderTypes_t11
{
  struct TypeBuilderTypes_t11a u1;
  struct TypeBuilderTypes_t11b u2;
} TypeBuilderTypes_t11;

extern const dds_topic_descriptor_t TypeBuilderTypes_t11_desc;

#define TypeBuilderTypes_t11__alloc() \
((TypeBuilderTypes_t11*) dds_alloc (sizeof (TypeBuilderTypes_t11)));

#define TypeBuilderTypes_t11_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t11_desc, (o))

typedef struct TypeBuilderTypes_t12a
{
  int32_t fa1;
} TypeBuilderTypes_t12a;

typedef struct TypeBuilderTypes_t12b
{
  int32_t fb1;
  struct TypeBuilderTypes_t12a fb2;
} TypeBuilderTypes_t12b;

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t12b
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t12b *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t12b;

#define dds_sequence_TypeBuilderTypes_t12b__alloc() \
((dds_sequence_TypeBuilderTypes_t12b*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t12b)));

#define dds_sequence_TypeBuilderTypes_t12b_allocbuf(l) \
((struct TypeBuilderTypes_t12b *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t12b)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED */

#ifndef DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED
#define DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED
typedef struct dds_sequence_sequence_TypeBuilderTypes_t12b
{
  uint32_t _maximum;
  uint32_t _length;
  dds_sequence_TypeBuilderTypes_t12b *_buffer;
  bool _release;
} dds_sequence_sequence_TypeBuilderTypes_t12b;

#define dds_sequence_sequence_TypeBuilderTypes_t12b__alloc() \
((dds_sequence_sequence_TypeBuilderTypes_t12b*) dds_alloc (sizeof (dds_sequence_sequence_TypeBuilderTypes_t12b)));

#define dds_sequence_sequence_TypeBuilderTypes_t12b_allocbuf(l) \
((dds_sequence_TypeBuilderTypes_t12b *) dds_alloc ((l) * sizeof (dds_sequence_TypeBuilderTypes_t12b)))
#endif /* DDS_SEQUENCE_SEQUENCE_TYPEBUILDERTYPES_T12B_DEFINED */

typedef struct TypeBuilderTypes_t12
{
  int32_t f1;
  int16_t f2;
  struct TypeBuilderTypes_t12a f3;
  struct TypeBuilderTypes_t12b f4;
  char (* f5)[6];
  struct TypeBuilderTypes_t12a f6;
  dds_sequence_sequence_TypeBuilderTypes_t12b f7[3];
  float f8[3][4];
  char * f9[5];
} TypeBuilderTypes_t12;

extern const dds_topic_descriptor_t TypeBuilderTypes_t12_desc;

#define TypeBuilderTypes_t12__alloc() \
((TypeBuilderTypes_t12*) dds_alloc (sizeof (TypeBuilderTypes_t12)));

#define TypeBuilderTypes_t12_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t12_desc, (o))

typedef struct TypeBuilderTypes_t13a
{
  char b1;
  struct TypeBuilderTypes_t1 b2;
  bool b3;
} TypeBuilderTypes_t13a;

typedef struct TypeBuilderTypes_t13
{
  struct TypeBuilderTypes_t13a parent;
  char f0;
  int64_t f1;
  struct TypeBuilderTypes_t1 f2;
  struct TypeBuilderTypes_t12 f3;
  struct TypeBuilderTypes_t11 f4;
} TypeBuilderTypes_t13;

extern const dds_topic_descriptor_t TypeBuilderTypes_t13_desc;

#define TypeBuilderTypes_t13__alloc() \
((TypeBuilderTypes_t13*) dds_alloc (sizeof (TypeBuilderTypes_t13)));

#define TypeBuilderTypes_t13_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t13_desc, (o))

typedef struct TypeBuilderTypes_t14a
{
  int32_t a1;
} TypeBuilderTypes_t14a;

typedef struct TypeBuilderTypes_t14b
{
  struct TypeBuilderTypes_t14a b1;
} TypeBuilderTypes_t14b;

typedef struct TypeBuilderTypes_t14c
{
  struct TypeBuilderTypes_t14b c1;
} TypeBuilderTypes_t14c;

typedef struct TypeBuilderTypes_t14
{
  struct TypeBuilderTypes_t14c f1;
} TypeBuilderTypes_t14;

extern const dds_topic_descriptor_t TypeBuilderTypes_t14_desc;

#define TypeBuilderTypes_t14__alloc() \
((TypeBuilderTypes_t14*) dds_alloc (sizeof (TypeBuilderTypes_t14)));

#define TypeBuilderTypes_t14_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t14_desc, (o))

typedef struct TypeBuilderTypes_t15a
{
  char _d;
  union
  {
    int32_t u1;
    char * u2;
    float u3;
  } _u;
} TypeBuilderTypes_t15a;

extern const dds_topic_descriptor_t TypeBuilderTypes_t15a_desc;

#define TypeBuilderTypes_t15a__alloc() \
((TypeBuilderTypes_t15a*) dds_alloc (sizeof (TypeBuilderTypes_t15a)));

#define TypeBuilderTypes_t15a_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t15a_desc, (o))

typedef struct TypeBuilderTypes_t15b
{
  int64_t _d;
  union
  {
    int32_t * u1;
    struct TypeBuilderTypes_t1 u2;
    struct TypeBuilderTypes_t2 * u3;
  } _u;
} TypeBuilderTypes_t15b;

extern const dds_topic_descriptor_t TypeBuilderTypes_t15b_desc;

#define TypeBuilderTypes_t15b__alloc() \
((TypeBuilderTypes_t15b*) dds_alloc (sizeof (TypeBuilderTypes_t15b)));

#define TypeBuilderTypes_t15b_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t15b_desc, (o))

typedef struct TypeBuilderTypes_t15c
{
  char * a1;
  char * a2;
  int64_t * a3;
  struct TypeBuilderTypes_t15a * a4;
  struct TypeBuilderTypes_t15b * a5;
} TypeBuilderTypes_t15c;

extern const dds_topic_descriptor_t TypeBuilderTypes_t15c_desc;

#define TypeBuilderTypes_t15c__alloc() \
((TypeBuilderTypes_t15c*) dds_alloc (sizeof (TypeBuilderTypes_t15c)));

#define TypeBuilderTypes_t15c_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t15c_desc, (o))

typedef struct TypeBuilderTypes_t15
{
  struct TypeBuilderTypes_t15c parent;
  struct TypeBuilderTypes_t15c * f1;
  TypeBuilderTypes_en * f2;
  TypeBuilderTypes_bm16 * f3;
} TypeBuilderTypes_t15;

extern const dds_topic_descriptor_t TypeBuilderTypes_t15_desc;

#define TypeBuilderTypes_t15__alloc() \
((TypeBuilderTypes_t15*) dds_alloc (sizeof (TypeBuilderTypes_t15)));

#define TypeBuilderTypes_t15_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t15_desc, (o))

typedef struct TypeBuilderTypes_t16
{
  char f1;
  int64_t f2;
  char f3;
} TypeBuilderTypes_t16;

extern const dds_topic_descriptor_t TypeBuilderTypes_t16_desc;

#define TypeBuilderTypes_t16__alloc() \
((TypeBuilderTypes_t16*) dds_alloc (sizeof (TypeBuilderTypes_t16)));

#define TypeBuilderTypes_t16_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t16_desc, (o))

typedef enum TypeBuilderTypes_en16
{
  TypeBuilderTypes_EN16_1,
  TypeBuilderTypes_EN16_2
} TypeBuilderTypes_en16;

#define TypeBuilderTypes_en16__alloc() \
((TypeBuilderTypes_en16*) dds_alloc (sizeof (TypeBuilderTypes_en16)));

typedef struct TypeBuilderTypes_t17
{
  TypeBuilderTypes_en16 _d;
  union
  {
    struct TypeBuilderTypes_t14 u1;
    struct TypeBuilderTypes_t15 u2;
  } _u;
} TypeBuilderTypes_t17;

extern const dds_topic_descriptor_t TypeBuilderTypes_t17_desc;

#define TypeBuilderTypes_t17__alloc() \
((TypeBuilderTypes_t17*) dds_alloc (sizeof (TypeBuilderTypes_t17)));

#define TypeBuilderTypes_t17_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t17_desc, (o))

typedef struct TypeBuilderTypes_t18
{
  int32_t f1;
} TypeBuilderTypes_t18;

extern const dds_topic_descriptor_t TypeBuilderTypes_t18_desc;

#define TypeBuilderTypes_t18__alloc() \
((TypeBuilderTypes_t18*) dds_alloc (sizeof (TypeBuilderTypes_t18)));

#define TypeBuilderTypes_t18_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t18_desc, (o))

typedef struct TypeBuilderTypes_t19_1
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} TypeBuilderTypes_t19_1;

#define TypeBuilderTypes_t19_1__alloc() \
((TypeBuilderTypes_t19_1*) dds_alloc (sizeof (TypeBuilderTypes_t19_1)));

#define TypeBuilderTypes_t19_1_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
typedef struct TypeBuilderTypes_t19_2
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} TypeBuilderTypes_t19_2;

#define TypeBuilderTypes_t19_2__alloc() \
((TypeBuilderTypes_t19_2*) dds_alloc (sizeof (TypeBuilderTypes_t19_2)));

#define TypeBuilderTypes_t19_2_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
typedef struct TypeBuilderTypes_t19
{
  TypeBuilderTypes_t19_2 f1;
  TypeBuilderTypes_t19_1 f2;
} TypeBuilderTypes_t19;

extern const dds_topic_descriptor_t TypeBuilderTypes_t19_desc;

#define TypeBuilderTypes_t19__alloc() \
((TypeBuilderTypes_t19*) dds_alloc (sizeof (TypeBuilderTypes_t19)));

#define TypeBuilderTypes_t19_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t19_desc, (o))

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

typedef struct TypeBuilderTypes_t20_1
{
  int16_t _d;
  union
  {
    dds_sequence_long u1;
    int16_t u2[3];
  } _u;
} TypeBuilderTypes_t20_1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t20_1_desc;

#define TypeBuilderTypes_t20_1__alloc() \
((TypeBuilderTypes_t20_1*) dds_alloc (sizeof (TypeBuilderTypes_t20_1)));

#define TypeBuilderTypes_t20_1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t20_1_desc, (o))

typedef struct TypeBuilderTypes_t20
{
  struct TypeBuilderTypes_t20_1 f1;
  int32_t f2;
} TypeBuilderTypes_t20;

extern const dds_topic_descriptor_t TypeBuilderTypes_t20_desc;

#define TypeBuilderTypes_t20__alloc() \
((TypeBuilderTypes_t20*) dds_alloc (sizeof (TypeBuilderTypes_t20)));

#define TypeBuilderTypes_t20_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t20_desc, (o))

typedef enum TypeBuilderTypes_t21_1
{
  TypeBuilderTypes_T21_1_0,
  TypeBuilderTypes_T21_1_1
} TypeBuilderTypes_t21_1;

#define TypeBuilderTypes_t21_1__alloc() \
((TypeBuilderTypes_t21_1*) dds_alloc (sizeof (TypeBuilderTypes_t21_1)));

typedef struct TypeBuilderTypes_t21_2
{
  int16_t _d;
  union
  {
    TypeBuilderTypes_t21_1 u1[3];
  } _u;
} TypeBuilderTypes_t21_2;

extern const dds_topic_descriptor_t TypeBuilderTypes_t21_2_desc;

#define TypeBuilderTypes_t21_2__alloc() \
((TypeBuilderTypes_t21_2*) dds_alloc (sizeof (TypeBuilderTypes_t21_2)));

#define TypeBuilderTypes_t21_2_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t21_2_desc, (o))

typedef struct TypeBuilderTypes_t21
{
  struct TypeBuilderTypes_t21_2 f1;
} TypeBuilderTypes_t21;

extern const dds_topic_descriptor_t TypeBuilderTypes_t21_desc;

#define TypeBuilderTypes_t21__alloc() \
((TypeBuilderTypes_t21*) dds_alloc (sizeof (TypeBuilderTypes_t21)));

#define TypeBuilderTypes_t21_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t21_desc, (o))

typedef struct TypeBuilderTypes_t22_1
{
  char f1[3];
} TypeBuilderTypes_t22_1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t22_1_desc;

#define TypeBuilderTypes_t22_1__alloc() \
((TypeBuilderTypes_t22_1*) dds_alloc (sizeof (TypeBuilderTypes_t22_1)));

#define TypeBuilderTypes_t22_1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t22_1_desc, (o))

typedef int32_t TypeBuilderTypes_arr_l[3];

#define TypeBuilderTypes_arr_l__alloc() \
((TypeBuilderTypes_arr_l*) dds_alloc (sizeof (TypeBuilderTypes_arr_l)));

typedef TypeBuilderTypes_arr_l TypeBuilderTypes_arr_l2[4];

#define TypeBuilderTypes_arr_l2__alloc() \
((TypeBuilderTypes_arr_l2*) dds_alloc (sizeof (TypeBuilderTypes_arr_l2)));

typedef TypeBuilderTypes_arr_l2 TypeBuilderTypes_arr_l3;

#define TypeBuilderTypes_arr_l3__alloc() \
((TypeBuilderTypes_arr_l3*) dds_alloc (sizeof (TypeBuilderTypes_arr_l3)));

typedef struct TypeBuilderTypes_t22
{
  int64_t f1[2][3];
  TypeBuilderTypes_arr_l3 f2;
  TypeBuilderTypes_arr_l3 f3[2];
  struct TypeBuilderTypes_t22_1 f4;
} TypeBuilderTypes_t22;

extern const dds_topic_descriptor_t TypeBuilderTypes_t22_desc;

#define TypeBuilderTypes_t22__alloc() \
((TypeBuilderTypes_t22*) dds_alloc (sizeof (TypeBuilderTypes_t22)));

#define TypeBuilderTypes_t22_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t22_desc, (o))

typedef char *TypeBuilderTypes_arr_s[2];

#define TypeBuilderTypes_arr_s__alloc() \
((TypeBuilderTypes_arr_s*) dds_alloc (sizeof (TypeBuilderTypes_arr_s)));

typedef TypeBuilderTypes_arr_s TypeBuilderTypes_arr_s2;

#define TypeBuilderTypes_arr_s2__alloc() \
((TypeBuilderTypes_arr_s2*) dds_alloc (sizeof (TypeBuilderTypes_arr_s2)));

typedef struct TypeBuilderTypes_t23
{
  TypeBuilderTypes_arr_s2 f1[2];
} TypeBuilderTypes_t23;

extern const dds_topic_descriptor_t TypeBuilderTypes_t23_desc;

#define TypeBuilderTypes_t23__alloc() \
((TypeBuilderTypes_t23*) dds_alloc (sizeof (TypeBuilderTypes_t23)));

#define TypeBuilderTypes_t23_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t23_desc, (o))

typedef struct TypeBuilderTypes_t24_1
{
  int32_t f1;
} TypeBuilderTypes_t24_1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t24_1_desc;

#define TypeBuilderTypes_t24_1__alloc() \
((TypeBuilderTypes_t24_1*) dds_alloc (sizeof (TypeBuilderTypes_t24_1)));

#define TypeBuilderTypes_t24_1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t24_1_desc, (o))

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t24_1
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t24_1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t24_1;

#define dds_sequence_TypeBuilderTypes_t24_1__alloc() \
((dds_sequence_TypeBuilderTypes_t24_1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t24_1)));

#define dds_sequence_TypeBuilderTypes_t24_1_allocbuf(l) \
((struct TypeBuilderTypes_t24_1 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t24_1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED */

typedef struct TypeBuilderTypes_t24_2
{
  uint8_t _d;
  union
  {
    int32_t a;
    struct TypeBuilderTypes_t24_1 b;
    dds_sequence_TypeBuilderTypes_t24_1 c;
  } _u;
} TypeBuilderTypes_t24_2;

extern const dds_topic_descriptor_t TypeBuilderTypes_t24_2_desc;

#define TypeBuilderTypes_t24_2__alloc() \
((TypeBuilderTypes_t24_2*) dds_alloc (sizeof (TypeBuilderTypes_t24_2)));

#define TypeBuilderTypes_t24_2_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t24_2_desc, (o))

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t24_1
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t24_1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t24_1;

#define dds_sequence_TypeBuilderTypes_t24_1__alloc() \
((dds_sequence_TypeBuilderTypes_t24_1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t24_1)));

#define dds_sequence_TypeBuilderTypes_t24_1_allocbuf(l) \
((struct TypeBuilderTypes_t24_1 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t24_1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t24_1
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t24_1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t24_1;

#define dds_sequence_TypeBuilderTypes_t24_1__alloc() \
((dds_sequence_TypeBuilderTypes_t24_1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t24_1)));

#define dds_sequence_TypeBuilderTypes_t24_1_allocbuf(l) \
((struct TypeBuilderTypes_t24_1 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t24_1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T24_2_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T24_2_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t24_2
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t24_2 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t24_2;

#define dds_sequence_TypeBuilderTypes_t24_2__alloc() \
((dds_sequence_TypeBuilderTypes_t24_2*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t24_2)));

#define dds_sequence_TypeBuilderTypes_t24_2_allocbuf(l) \
((struct TypeBuilderTypes_t24_2 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t24_2)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T24_2_DEFINED */

#ifndef DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
#define DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED
typedef struct dds_sequence_TypeBuilderTypes_t24_1
{
  uint32_t _maximum;
  uint32_t _length;
  struct TypeBuilderTypes_t24_1 *_buffer;
  bool _release;
} dds_sequence_TypeBuilderTypes_t24_1;

#define dds_sequence_TypeBuilderTypes_t24_1__alloc() \
((dds_sequence_TypeBuilderTypes_t24_1*) dds_alloc (sizeof (dds_sequence_TypeBuilderTypes_t24_1)));

#define dds_sequence_TypeBuilderTypes_t24_1_allocbuf(l) \
((struct TypeBuilderTypes_t24_1 *) dds_alloc ((l) * sizeof (struct TypeBuilderTypes_t24_1)))
#endif /* DDS_SEQUENCE_TYPEBUILDERTYPES_T24_1_DEFINED */

typedef struct TypeBuilderTypes_t24
{
  uint8_t _d;
  union
  {
    dds_sequence_TypeBuilderTypes_t24_1 u1;
    struct TypeBuilderTypes_t24_1 u2;
    struct TypeBuilderTypes_t24_1 u3[2];
    dds_sequence_TypeBuilderTypes_t24_1 u4[2];
    dds_sequence_TypeBuilderTypes_t24_2 s1;
    struct TypeBuilderTypes_t24_2 s2;
    dds_sequence_TypeBuilderTypes_t24_1 u99;
  } _u;
} TypeBuilderTypes_t24;

extern const dds_topic_descriptor_t TypeBuilderTypes_t24_desc;

#define TypeBuilderTypes_t24__alloc() \
((TypeBuilderTypes_t24*) dds_alloc (sizeof (TypeBuilderTypes_t24)));

#define TypeBuilderTypes_t24_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t24_desc, (o))

typedef struct TypeBuilderTypes_t25_1
{
  int32_t _d;
  union
  {
    char u1[10];
  } _u;
} TypeBuilderTypes_t25_1;

extern const dds_topic_descriptor_t TypeBuilderTypes_t25_1_desc;

#define TypeBuilderTypes_t25_1__alloc() \
((TypeBuilderTypes_t25_1*) dds_alloc (sizeof (TypeBuilderTypes_t25_1)));

#define TypeBuilderTypes_t25_1_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t25_1_desc, (o))

typedef struct TypeBuilderTypes_t25
{
  struct TypeBuilderTypes_t25_1 f1;
} TypeBuilderTypes_t25;

extern const dds_topic_descriptor_t TypeBuilderTypes_t25_desc;

#define TypeBuilderTypes_t25__alloc() \
((TypeBuilderTypes_t25*) dds_alloc (sizeof (TypeBuilderTypes_t25)));

#define TypeBuilderTypes_t25_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t25_desc, (o))

typedef struct TypeBuilderTypes_t26_1
{
  uint8_t _d;
  union
  {
    int32_t u1;
    int32_t u2;
  } _u;
} TypeBuilderTypes_t26_1;

typedef struct TypeBuilderTypes_t26
{
  struct TypeBuilderTypes_t26_1 f1;
} TypeBuilderTypes_t26;

extern const dds_topic_descriptor_t TypeBuilderTypes_t26_desc;

#define TypeBuilderTypes_t26__alloc() \
((TypeBuilderTypes_t26*) dds_alloc (sizeof (TypeBuilderTypes_t26)));

#define TypeBuilderTypes_t26_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t26_desc, (o))

typedef enum TypeBuilderTypes_en27
{
  TypeBuilderTypes_E27_3 = 4,
  TypeBuilderTypes_E27_1,
  TypeBuilderTypes_E27_2 = 3
} TypeBuilderTypes_en27;

#define TypeBuilderTypes_en27__alloc() \
((TypeBuilderTypes_en27*) dds_alloc (sizeof (TypeBuilderTypes_en27)));

typedef struct TypeBuilderTypes_t27_1
{
  TypeBuilderTypes_en27 _d;
  union
  {
    int32_t u1;
    int32_t u3;
    int32_t ud;
  } _u;
} TypeBuilderTypes_t27_1;

typedef struct TypeBuilderTypes_t27
{
  struct TypeBuilderTypes_t27_1 f1;
} TypeBuilderTypes_t27;

extern const dds_topic_descriptor_t TypeBuilderTypes_t27_desc;

#define TypeBuilderTypes_t27__alloc() \
((TypeBuilderTypes_t27*) dds_alloc (sizeof (TypeBuilderTypes_t27)));

#define TypeBuilderTypes_t27_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t27_desc, (o))

typedef struct TypeBuilderTypes_t28
{
  char * f1;
  char f2[4];
} TypeBuilderTypes_t28;

extern const dds_topic_descriptor_t TypeBuilderTypes_t28_desc;

#define TypeBuilderTypes_t28__alloc() \
((TypeBuilderTypes_t28*) dds_alloc (sizeof (TypeBuilderTypes_t28)));

#define TypeBuilderTypes_t28_free(d,o) \
dds_sample_free ((d), &TypeBuilderTypes_t28_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_TYPEBUILDERTYPES_H_29B1475AF9AD2FF9D7ADF607B4C3EF8F */
