/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: WriteTypes.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/WriteTypes.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_WRITETYPES_H_36764694CF1B93C26B572C68176149A1
#define DDSC_WRITETYPES_H_36764694CF1B93C26B572C68176149A1

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct WriteTypes_a
{
  uint8_t k[3];
  uint64_t ll;
} WriteTypes_a;

extern const dds_topic_descriptor_t WriteTypes_a_desc;

#define WriteTypes_a__alloc() \
((WriteTypes_a*) dds_alloc (sizeof (WriteTypes_a)));

#define WriteTypes_a_free(d,o) \
dds_sample_free ((d), &WriteTypes_a_desc, (o))

typedef struct WriteTypes_b
{
  uint16_t k[3];
  uint64_t ll;
} WriteTypes_b;

extern const dds_topic_descriptor_t WriteTypes_b_desc;

#define WriteTypes_b__alloc() \
((WriteTypes_b*) dds_alloc (sizeof (WriteTypes_b)));

#define WriteTypes_b_free(d,o) \
dds_sample_free ((d), &WriteTypes_b_desc, (o))

typedef struct WriteTypes_c
{
  uint32_t k[3];
  uint64_t ll;
} WriteTypes_c;

extern const dds_topic_descriptor_t WriteTypes_c_desc;

#define WriteTypes_c__alloc() \
((WriteTypes_c*) dds_alloc (sizeof (WriteTypes_c)));

#define WriteTypes_c_free(d,o) \
dds_sample_free ((d), &WriteTypes_c_desc, (o))

typedef struct WriteTypes_d
{
  uint64_t k[3];
  uint64_t ll;
} WriteTypes_d;

extern const dds_topic_descriptor_t WriteTypes_d_desc;

#define WriteTypes_d__alloc() \
((WriteTypes_d*) dds_alloc (sizeof (WriteTypes_d)));

#define WriteTypes_d_free(d,o) \
dds_sample_free ((d), &WriteTypes_d_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_WRITETYPES_H_36764694CF1B93C26B572C68176149A1 */
