/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: XSpaceNoTypeInfo.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/XSpaceNoTypeInfo.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_XSPACENOTYPEINFO_H_6D61F3A4A67783DF5F763DE0A0DCB41C
#define DDSC_XSPACENOTYPEINFO_H_6D61F3A4A67783DF5F763DE0A0DCB41C

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct XSpaceNoTypeInfo_t1
{
  int32_t long_1;
} XSpaceNoTypeInfo_t1;

extern const dds_topic_descriptor_t XSpaceNoTypeInfo_t1_desc;

#define XSpaceNoTypeInfo_t1__alloc() \
((XSpaceNoTypeInfo_t1*) dds_alloc (sizeof (XSpaceNoTypeInfo_t1)));

#define XSpaceNoTypeInfo_t1_free(d,o) \
dds_sample_free ((d), &XSpaceNoTypeInfo_t1_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_XSPACENOTYPEINFO_H_6D61F3A4A67783DF5F763DE0A0DCB41C */
