/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: XSpaceMustUnderstand.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/XSpaceMustUnderstand.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_XSPACEMUSTUNDERSTAND_H_CAC4BB2EA1E4AB873EC29EB8E720DBC9
#define DDSC_XSPACEMUSTUNDERSTAND_H_CAC4BB2EA1E4AB873EC29EB8E720DBC9

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct XSpaceMustUnderstand_rd1
{
  int32_t f1;
} XSpaceMustUnderstand_rd1;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_rd1_desc;

#define XSpaceMustUnderstand_rd1__alloc() \
((XSpaceMustUnderstand_rd1*) dds_alloc (sizeof (XSpaceMustUnderstand_rd1)));

#define XSpaceMustUnderstand_rd1_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_rd1_desc, (o))

typedef struct XSpaceMustUnderstand_wr1_1
{
  int32_t f1;
  int32_t f2;
} XSpaceMustUnderstand_wr1_1;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_1_desc;

#define XSpaceMustUnderstand_wr1_1__alloc() \
((XSpaceMustUnderstand_wr1_1*) dds_alloc (sizeof (XSpaceMustUnderstand_wr1_1)));

#define XSpaceMustUnderstand_wr1_1_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_wr1_1_desc, (o))

typedef struct XSpaceMustUnderstand_wr1_2
{
  int32_t f1;
} XSpaceMustUnderstand_wr1_2;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_2_desc;

#define XSpaceMustUnderstand_wr1_2__alloc() \
((XSpaceMustUnderstand_wr1_2*) dds_alloc (sizeof (XSpaceMustUnderstand_wr1_2)));

#define XSpaceMustUnderstand_wr1_2_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_wr1_2_desc, (o))

typedef struct XSpaceMustUnderstand_wr1_3
{
  int32_t f1;
  int32_t * f2;
} XSpaceMustUnderstand_wr1_3;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_3_desc;

#define XSpaceMustUnderstand_wr1_3__alloc() \
((XSpaceMustUnderstand_wr1_3*) dds_alloc (sizeof (XSpaceMustUnderstand_wr1_3)));

#define XSpaceMustUnderstand_wr1_3_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_wr1_3_desc, (o))

typedef struct XSpaceMustUnderstand_wr1_4
{
  int32_t * f1;
} XSpaceMustUnderstand_wr1_4;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_4_desc;

#define XSpaceMustUnderstand_wr1_4__alloc() \
((XSpaceMustUnderstand_wr1_4*) dds_alloc (sizeof (XSpaceMustUnderstand_wr1_4)));

#define XSpaceMustUnderstand_wr1_4_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_wr1_4_desc, (o))

typedef struct XSpaceMustUnderstand_n2
{
  int32_t f1;
} XSpaceMustUnderstand_n2;

typedef struct XSpaceMustUnderstand_n2_mu
{
  int32_t f1;
  int32_t * f2;
} XSpaceMustUnderstand_n2_mu;

typedef struct XSpaceMustUnderstand_rd2
{
  struct XSpaceMustUnderstand_n2 f1;
} XSpaceMustUnderstand_rd2;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_rd2_desc;

#define XSpaceMustUnderstand_rd2__alloc() \
((XSpaceMustUnderstand_rd2*) dds_alloc (sizeof (XSpaceMustUnderstand_rd2)));

#define XSpaceMustUnderstand_rd2_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_rd2_desc, (o))

typedef struct XSpaceMustUnderstand_wr2_1
{
  struct XSpaceMustUnderstand_n2_mu f1;
} XSpaceMustUnderstand_wr2_1;

extern const dds_topic_descriptor_t XSpaceMustUnderstand_wr2_1_desc;

#define XSpaceMustUnderstand_wr2_1__alloc() \
((XSpaceMustUnderstand_wr2_1*) dds_alloc (sizeof (XSpaceMustUnderstand_wr2_1)));

#define XSpaceMustUnderstand_wr2_1_free(d,o) \
dds_sample_free ((d), &XSpaceMustUnderstand_wr2_1_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_XSPACEMUSTUNDERSTAND_H_CAC4BB2EA1E4AB873EC29EB8E720DBC9 */
