/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: XSpaceEnum.h
  Source: /home/wangkunlin/Desktop/cyclonedds/debug/bin/idl_analyze/XSpaceEnum.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_XSPACEENUM_H_0D528415E3E8B4A9E9F64DEFD513C521
#define DDSC_XSPACEENUM_H_0D528415E3E8B4A9E9F64DEFD513C521

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum XSpaceEnum_enum_f
{
  XSpaceEnum_F1,
  XSpaceEnum_F2,
  XSpaceEnum_F3
} XSpaceEnum_enum_f;

#define XSpaceEnum_enum_f__alloc() \
((XSpaceEnum_enum_f*) dds_alloc (sizeof (XSpaceEnum_enum_f)));

typedef enum XSpaceEnum_enum_a
{
  XSpaceEnum_A1,
  XSpaceEnum_A2,
  XSpaceEnum_A3
} XSpaceEnum_enum_a;

#define XSpaceEnum_enum_a__alloc() \
((XSpaceEnum_enum_a*) dds_alloc (sizeof (XSpaceEnum_enum_a)));

typedef struct XSpaceEnum_rd1
{
  XSpaceEnum_enum_f f1;
} XSpaceEnum_rd1;

extern const dds_topic_descriptor_t XSpaceEnum_rd1_desc;

#define XSpaceEnum_rd1__alloc() \
((XSpaceEnum_rd1*) dds_alloc (sizeof (XSpaceEnum_rd1)));

#define XSpaceEnum_rd1_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_rd1_desc, (o))

typedef struct XSpaceEnum_wr1_1
{
  XSpaceEnum_enum_f f1;
} XSpaceEnum_wr1_1;

extern const dds_topic_descriptor_t XSpaceEnum_wr1_1_desc;

#define XSpaceEnum_wr1_1__alloc() \
((XSpaceEnum_wr1_1*) dds_alloc (sizeof (XSpaceEnum_wr1_1)));

#define XSpaceEnum_wr1_1_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_wr1_1_desc, (o))

typedef struct XSpaceEnum_wr1_2
{
  XSpaceEnum_enum_a f1;
} XSpaceEnum_wr1_2;

extern const dds_topic_descriptor_t XSpaceEnum_wr1_2_desc;

#define XSpaceEnum_wr1_2__alloc() \
((XSpaceEnum_wr1_2*) dds_alloc (sizeof (XSpaceEnum_wr1_2)));

#define XSpaceEnum_wr1_2_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_wr1_2_desc, (o))

typedef struct XSpaceEnum_rd2
{
  XSpaceEnum_enum_a f1;
} XSpaceEnum_rd2;

extern const dds_topic_descriptor_t XSpaceEnum_rd2_desc;

#define XSpaceEnum_rd2__alloc() \
((XSpaceEnum_rd2*) dds_alloc (sizeof (XSpaceEnum_rd2)));

#define XSpaceEnum_rd2_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_rd2_desc, (o))

typedef struct XSpaceEnum_wr2_1
{
  XSpaceEnum_enum_a f1;
} XSpaceEnum_wr2_1;

extern const dds_topic_descriptor_t XSpaceEnum_wr2_1_desc;

#define XSpaceEnum_wr2_1__alloc() \
((XSpaceEnum_wr2_1*) dds_alloc (sizeof (XSpaceEnum_wr2_1)));

#define XSpaceEnum_wr2_1_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_wr2_1_desc, (o))

typedef struct XSpaceEnum_wr2_2
{
  XSpaceEnum_enum_f f1;
} XSpaceEnum_wr2_2;

extern const dds_topic_descriptor_t XSpaceEnum_wr2_2_desc;

#define XSpaceEnum_wr2_2__alloc() \
((XSpaceEnum_wr2_2*) dds_alloc (sizeof (XSpaceEnum_wr2_2)));

#define XSpaceEnum_wr2_2_free(d,o) \
dds_sample_free ((d), &XSpaceEnum_wr2_2_desc, (o))

typedef enum XSpaceEnumPlus_enum_f_plus
{
  XSpaceEnumPlus_F1,
  XSpaceEnumPlus_F2,
  XSpaceEnumPlus_F3,
  XSpaceEnumPlus_F4
} XSpaceEnumPlus_enum_f_plus;

#define XSpaceEnumPlus_enum_f_plus__alloc() \
((XSpaceEnumPlus_enum_f_plus*) dds_alloc (sizeof (XSpaceEnumPlus_enum_f_plus)));

typedef enum XSpaceEnumPlus_enum_a_plus
{
  XSpaceEnumPlus_A1,
  XSpaceEnumPlus_A2,
  XSpaceEnumPlus_A3,
  XSpaceEnumPlus_A4
} XSpaceEnumPlus_enum_a_plus;

#define XSpaceEnumPlus_enum_a_plus__alloc() \
((XSpaceEnumPlus_enum_a_plus*) dds_alloc (sizeof (XSpaceEnumPlus_enum_a_plus)));

typedef struct XSpaceEnumPlus_wr1_3
{
  XSpaceEnumPlus_enum_f_plus f1;
} XSpaceEnumPlus_wr1_3;

extern const dds_topic_descriptor_t XSpaceEnumPlus_wr1_3_desc;

#define XSpaceEnumPlus_wr1_3__alloc() \
((XSpaceEnumPlus_wr1_3*) dds_alloc (sizeof (XSpaceEnumPlus_wr1_3)));

#define XSpaceEnumPlus_wr1_3_free(d,o) \
dds_sample_free ((d), &XSpaceEnumPlus_wr1_3_desc, (o))

typedef struct XSpaceEnumPlus_wr2_3
{
  XSpaceEnumPlus_enum_a_plus f1;
} XSpaceEnumPlus_wr2_3;

extern const dds_topic_descriptor_t XSpaceEnumPlus_wr2_3_desc;

#define XSpaceEnumPlus_wr2_3__alloc() \
((XSpaceEnumPlus_wr2_3*) dds_alloc (sizeof (XSpaceEnumPlus_wr2_3)));

#define XSpaceEnumPlus_wr2_3_free(d,o) \
dds_sample_free ((d), &XSpaceEnumPlus_wr2_3_desc, (o))

typedef enum XSpaceEnumMin_enum_f_min
{
  XSpaceEnumMin_F1,
  XSpaceEnumMin_F2
} XSpaceEnumMin_enum_f_min;

#define XSpaceEnumMin_enum_f_min__alloc() \
((XSpaceEnumMin_enum_f_min*) dds_alloc (sizeof (XSpaceEnumMin_enum_f_min)));

typedef enum XSpaceEnumMin_enum_a_min
{
  XSpaceEnumMin_A1,
  XSpaceEnumMin_A2
} XSpaceEnumMin_enum_a_min;

#define XSpaceEnumMin_enum_a_min__alloc() \
((XSpaceEnumMin_enum_a_min*) dds_alloc (sizeof (XSpaceEnumMin_enum_a_min)));

typedef struct XSpaceEnumMin_wr1_4
{
  XSpaceEnumMin_enum_f_min f1;
} XSpaceEnumMin_wr1_4;

extern const dds_topic_descriptor_t XSpaceEnumMin_wr1_4_desc;

#define XSpaceEnumMin_wr1_4__alloc() \
((XSpaceEnumMin_wr1_4*) dds_alloc (sizeof (XSpaceEnumMin_wr1_4)));

#define XSpaceEnumMin_wr1_4_free(d,o) \
dds_sample_free ((d), &XSpaceEnumMin_wr1_4_desc, (o))

typedef struct XSpaceEnumMin_wr2_4
{
  XSpaceEnumMin_enum_a_min f1;
} XSpaceEnumMin_wr2_4;

extern const dds_topic_descriptor_t XSpaceEnumMin_wr2_4_desc;

#define XSpaceEnumMin_wr2_4__alloc() \
((XSpaceEnumMin_wr2_4*) dds_alloc (sizeof (XSpaceEnumMin_wr2_4)));

#define XSpaceEnumMin_wr2_4_free(d,o) \
dds_sample_free ((d), &XSpaceEnumMin_wr2_4_desc, (o))

typedef enum XSpaceEnumLabel_enum_f_label
{
  XSpaceEnumLabel_F1,
  XSpaceEnumLabel_FFF2,
  XSpaceEnumLabel_F3
} XSpaceEnumLabel_enum_f_label;

#define XSpaceEnumLabel_enum_f_label__alloc() \
((XSpaceEnumLabel_enum_f_label*) dds_alloc (sizeof (XSpaceEnumLabel_enum_f_label)));

typedef enum XSpaceEnumLabel_enum_a_label
{
  XSpaceEnumLabel_A1,
  XSpaceEnumLabel_AAA2,
  XSpaceEnumLabel_A3
} XSpaceEnumLabel_enum_a_label;

#define XSpaceEnumLabel_enum_a_label__alloc() \
((XSpaceEnumLabel_enum_a_label*) dds_alloc (sizeof (XSpaceEnumLabel_enum_a_label)));

typedef struct XSpaceEnumLabel_wr1_5
{
  XSpaceEnumLabel_enum_f_label f1;
} XSpaceEnumLabel_wr1_5;

extern const dds_topic_descriptor_t XSpaceEnumLabel_wr1_5_desc;

#define XSpaceEnumLabel_wr1_5__alloc() \
((XSpaceEnumLabel_wr1_5*) dds_alloc (sizeof (XSpaceEnumLabel_wr1_5)));

#define XSpaceEnumLabel_wr1_5_free(d,o) \
dds_sample_free ((d), &XSpaceEnumLabel_wr1_5_desc, (o))

typedef struct XSpaceEnumLabel_wr2_5
{
  XSpaceEnumLabel_enum_a_label f1;
} XSpaceEnumLabel_wr2_5;

extern const dds_topic_descriptor_t XSpaceEnumLabel_wr2_5_desc;

#define XSpaceEnumLabel_wr2_5__alloc() \
((XSpaceEnumLabel_wr2_5*) dds_alloc (sizeof (XSpaceEnumLabel_wr2_5)));

#define XSpaceEnumLabel_wr2_5_free(d,o) \
dds_sample_free ((d), &XSpaceEnumLabel_wr2_5_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_XSPACEENUM_H_0D528415E3E8B4A9E9F64DEFD513C521 */
